### ISSUE TITLE
Can you just write readme brother for this. i am totally ok i will be responsible for it

### ISSUE THREAD

**Issue by mantri8565** [Puyodead1/udemy-downloader#1]

**Comment by mantri8565** [comment]
Explain the steps i am totally ok i will be responsible for it

**Comment by Puyodead1** [comment]
1. you need to open the network tab, and find the index.mpd file url
2. open the `dashdownloader_multisegment.py` file and replace ``mpd url`` with the url
![mpd url](https://i.imgur.com/YfGSPKd.png)
3. Change the video title and output path to whatever you want the video to be called
![title](https://i.imgur.com/lymSmag.png)
``175. Inverse Transforming Vectors`` is what your would replace
4. run ``python dashdownloader_multisegment.py`` in the terminal to start the download.

make sure you have ffmpeg and mp4decrypt installed in your path

**Comment by Puyodead1** [comment]
Im working on downloading entire courses automatically, just gotta finish the drm part and ill push the update to github

**Comment by Puyodead1** [comment]
okay, the new code has been pushed. it now downloads the entire course, Non-DRM videos and DRM videos. readme has been updated also.

**Comment by kr1tx** [comment]
I can't find mpd file!
