### ISSUE TITLE
How to get Decryption Key ID & Decryption Key?

### ISSUE THREAD

**Issue by syahnetwork** [Puyodead1/udemy-downloader#10]
thank you so much for this app , really helpful since udemy has updated their policy which caused major disappointment

**Comment by Puyodead1** [comment]
As I said in the README, its up to you to acquire the key and key ID. I don't want to have instructions for it that could get the repository issued a DMCA take down. The most I will say is that there's a Chrome extension that you have to use.

**Comment by syahnetwork** [comment]
yes thank you , i will look into it right away

**Comment by Parth-Consul** [comment]
> yes thank you for the clue , i will look into it right away

bro, can you pls tell me the chrome extension name?

**Comment by Puyodead1** [comment]
> > yes thank you for the clue , i will look into it right away
> 
> 
> 
> bro, can you pls tell me the chrome extension name?
> 
> 

Won't work
