### ISSUE TITLE
[Bug]: KID and ID do not appear in console, video with DRM protected cannot load as before suddenly

### ISSUE THREAD

**Issue by 7ang** [Puyodead1/udemy-downloader#100]
### What happened?

after replace widevinecdm.dll (version 2209) of chrome, it works fine for couples of day, but it seems breakdown today
it is not your scripts problem, seems udemy have update something?

### Expected Result

show kid and id in console

### Branch

master/main

**Comment by Puyodead1** [comment]
Not an issue with my script
