### ISSUE TITLE
wiki link dont work

### ISSUE THREAD

**Issue by mahdisky** [Puyodead1/udemy-downloader#102]
### What happened?

this link dosnt work
https://github.com/Puyodead1/udemy-downloader/wiki/Downgrade-CDM-to-2209-on-Chrome-(Windows)

### Expected Result

work like 
https://github.com/Puyodead1/udemy-downloader/wiki/Downgrade-CDM-to-2209-on-Chrome-(Windows)

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
It works fine
