### ISSUE TITLE
Feature request: Automate obtaining course id from url

### ISSUE THREAD

**Issue by asdfmonster261** [Puyodead1/udemy-downloader#11]
Basically instead of the command looking like this 
`python .\main.py -c 3724963`

It would look like this 
`python .\main.py -c https://udemy.com/course/totallyrealcourse`

**Comment by Puyodead1** [comment]
I'll look into this

**Comment by Puyodead1** [comment]
Added to 0782c42df7f351c50baf5f9d58902f77898ff990
will merge to master once I know there's no issues
