### ISSUE TITLE
How to download Udemy videos (I have the Decrypt Keys)

### ISSUE THREAD

**Issue by rajhlinux** [Puyodead1/udemy-downloader#111]
Hello,

I was finally able to find a way to obtain decryption keys.

Now how exactly do I download subscription videos that I paid for which are DRM Widevine protected?

I placed the KEY ID and KEY to the "keyfile.example.json" file... whats next?

Do I also need the Aquire Bearer Token?

Is it possible someone can place the syntax parameters or a tutorial.

Thanks.

**Comment by Puyodead1** [comment]
The readme has examples of commands, and information on usage.

**Comment by CHITTIMOTU** [comment]
> Hello,
> 
> I was finally able to find a way to obtain decryption keys.
> 
> Now how exactly do I use download subscription videos that I paid for which are DRM Widevine protected?
> 
> I placed the KEY ID and KEY to the "keyfile.example.json" file... whats next?
> 
> Do I also need the Aquire Bearer Token?
> 
> Is it possible someone can place the syntax parameters or a tutorial.
> 
> Thanks.

I know i am asking un-supported request by @Puyodead1 . I respect his support 
but @rajhlinux  can you please please help me with the instructions /at list hint (working chrome extension name /link??)  to get the Decrypt Keys.
i request you to share it on "chittimotunaveen@gmail.com"
i am a college faculty  and share Udemy video's to my students at free of cost, 
also i can share my barer token, so you can also get my purchased coerces.

**Comment by rajhlinux** [comment]
> The readme has examples of commands, and information on usage.

I checked the readme.md file and do not see much info on decrypt key and its way of usage.

**Comment by Puyodead1** [comment]
> > The readme has examples of commands, and information on usage.
> 
> I checked the readme.md file and do not see much info on decrypt key and its way of usage.

Yes, as the readme says, its up to you to get them. but there is extensive information on how to setup the program and use it

**Comment by rajhlinux** [comment]
> > Hello,
> > I was finally able to find a way to obtain decryption keys.
> > Now how exactly do I use download subscription videos that I paid for which are DRM Widevine protected?
> > I placed the KEY ID and KEY to the "keyfile.example.json" file... whats next?
> > Do I also need the Aquire Bearer Token?
> > Is it possible someone can place the syntax parameters or a tutorial.
> > Thanks.
> 
> I know i am asking un-supported request by @Puyodead1 . I respect his support but @rajhlinux can you please please help me with the instructions /at list hint (working chrome extension name /link??) to get the Decrypt Keys. i request you to share it on "[chittimotunaveen@gmail.com](mailto:chittimotunaveen@gmail.com)" i am a college faculty and share Udemy video's to my students at free of cost, also i can share my barer token, so you can also get my purchased coerces.

I do not support you giving professional content to students for free, this harms the author.

When I download my paid courses, I never share it because it hurts the Udemy's ecology to make professional content. I support DRM and wish DRM could never be easily broken by the mass public and I use piracy tactics to help me and not harm authors/original content creators.

Just as Puyodead1 does for his users, I'll have do the same for you, can't help you but will say that you are asking at the wrong place. Use "google" it is your friend, you'll find the "methods" how it's done... best believe it ain't easy and no web "extension" will work, been there and done it. 

The last thing anyone would want is google and Udemy changing/updating their protocol systems and algorithms when mass free loaders starts striping DRM again.

**Comment by rajhlinux** [comment]
> > > The readme has examples of commands, and information on usage.
> > 
> > 
> > I checked the readme.md file and do not see much info on decrypt key and its way of usage.
> 
> Yes, as the readme says, its up to you to get them. but there is extensive information on how to setup the program and use it

I know how to get the decrypt keys, that is not the issue.

Just would like to know how I apply it to the script. The readme seems a bit confusing and it does talk much how to set it up for downloading DRM content with the decrypt keys applied.

**Comment by Puyodead1** [comment]
> > > > The readme has examples of commands, and information on usage.
> > > 
> > > 
> > > I checked the readme.md file and do not see much info on decrypt key and its way of usage.
> > 
> > 
> > Yes, as the readme says, its up to you to get them. but there is extensive information on how to setup the program and use it
> 
> I know how to get the decrypt keys, that is not the issue.
> 
> Just would like to know how I apply it to the script. The readme seems a bit confusing and it does talk much how to set it up for downloading DRM content with the decrypt keys applied.

> does talk much how to set it up for downloading DRM content with the decrypt keys applied.
(assuming typo), yes it does, it tells you exactly what to do with the keys, and how to run the script.

**Comment by Puyodead1** [comment]
https://github.com/Puyodead1/udemy-downloader#setting-up
https://github.com/Puyodead1/udemy-downloader#key-id-and-key
https://github.com/Puyodead1/udemy-downloader#advanced-usage

**Comment by rajhlinux** [comment]
> > > > > The readme has examples of commands, and information on usage.
> > > > 
> > > > 
> > > > I checked the readme.md file and do not see much info on decrypt key and its way of usage.
> > > 
> > > 
> > > Yes, as the readme says, its up to you to get them. but there is extensive information on how to setup the program and use it
> > 
> > 
> > I know how to get the decrypt keys, that is not the issue.
> > Just would like to know how I apply it to the script. The readme seems a bit confusing and it does talk much how to set it up for downloading DRM content with the decrypt keys applied.
> 
> > does talk much how to set it up for downloading DRM content with the decrypt keys applied.
> 
> (assuming typo), yes it does, it tells you exactly what to do with the keys, and how to run the script.

Sorry it was a typo, wanted to say does "not".

**Comment by rajhlinux** [comment]
`python main.py -c <Course URL> --download-assets`

with the above link syntax, I can download lectures? what exactly are "assets"?

with the decrypt key and key id into the keyfile.json, everything is done passively when downloading?

**Comment by rajhlinux** [comment]
What exactly is bearer token? I never use "udemy-dl"... do I need to use it?

**Comment by Puyodead1** [comment]
> `python main.py -c <Course URL> --download-assets`
> 
> with the above link syntax, I can download lectures? what exactly are "assets"?
> 
> with the decrypt key and key id into the keyfile.json, everything is done passively when downloading?

yes, Assets are things like pdfs, mp3s, images, etc

**Comment by Puyodead1** [comment]
> What exactly is bearer token? I never use "udemy-dl"... do I need to use it?

its for authentication, you need to get it from your browser after logging in by following the guide

**Comment by rajhlinux** [comment]
> > What exactly is bearer token? I never use "udemy-dl"... do I need to use it?
> 
> its for authentication, you need to get it from your browser after logging in by following the guide

Alright, if I do not use bearer token, I would not be able to download DRM paid content at all?

**Comment by Puyodead1** [comment]
> > > What exactly is bearer token? I never use "udemy-dl"... do I need to use it?
> > 
> > 
> > its for authentication, you need to get it from your browser after logging in by following the guide
> 
> Alright, if I do not use bearer token, I would not be able to download DRM paid content at all?

no, there is a reason its a requirement

**Comment by rajhlinux** [comment]
I have also downloaded the following and installed manually on windows, do I need somehow have their usage directly available with the window's command prompt PATH environment?:

[ffmpeg](https://www.ffmpeg.org/) - This tool is also available in Linux package repositories

[aria2/aria2c](https://github.com/aria2/aria2/) - This tool is also available in Linux package repositories

[shaka-packager](https://github.com/google/shaka-packager/releases/latest)

[yt-dlp](https://github.com/yt-dlp/yt-dlp/) - This tool is also available in Linux package repositories, but can also be installed using pip if desired (pip install yt-dlp)

**Comment by Puyodead1** [comment]
please read the full readme in detail... 
> you will need to ensure they are in your systems path and that typing their name in a terminal invokes them.

**Comment by rajhlinux** [comment]
in the ".env" file I placed the "access_token" like this:

`UDEMY_BEARER=imd8tm42w3ITDYwDY9b7qsAfTjau1111ilECWnBc`

I got "access_token" value as: 

"imd8tm42w3ITDYwDY9b7qsAfTjau1111ilECWnBc" 

from developer tools, applications, cookies --> udemy.com --> "access_token" and got that value above.

is this the correct syntax for adding the bearer token in the ".env" file?

**Comment by Puyodead1** [comment]
do not post your access token publicly, anyone can use it to access your account.

**Comment by rajhlinux** [comment]
Alright,

Is this the correct way of placing the "bearer token" (AKA access_token) value to the ".env" file?:

UDEMY_BEARER=fosdoifjsdjfsdijfisdjfsdpsdfdsfsd

(The token is gibberish).

**Comment by rajhlinux** [comment]
Also is this the correct way of placing the decrypt ID and decrypt KEY ID as well to the "keyfile.json" ?:

```
{
  dasdasdasdasdasdasdasdasdasdasd : sadasdasdasdasdasdasdasdddasdas
}
```
The ID on the left is the "Decrypt Key ID", is this the ID used to get the PSSH? (I know not to put the PSSH here).

The ID on the right, is the "Decrypt Key", this is where the actual decryption key is placed which is obtained from the CDM?

**Comment by Puyodead1** [comment]
https://github.com/Puyodead1/udemy-downloader#key-id-and-key
