### ISSUE TITLE
shaka-packager 

### ISSUE THREAD

**Issue by rajhlinux** [Puyodead1/udemy-downloader#112]
shaka-packager executable is named as "packager-win-x64.exe"

do I need to change it "shaka-packager.exe"?

Because on windows cmd path only initiates the executable based on it's ".exe" name.

**Comment by Puyodead1** [comment]
yes

**Comment by rajhlinux** [comment]
Alright and for "yt-dlp"

I have it as "yt-dlp.exe"

This is also correct?

**Comment by Puyodead1** [comment]
yes
