### ISSUE TITLE
"Traceback" issue

### ISSUE THREAD

**Issue by rajhlinux** [Puyodead1/udemy-downloader#113]
When I type this command:

`C:\Users\Admin\Downloads\udemy\udemy-downloader-master>python main.py -c https://www.udemy.com/course/day-trading-strategies-day-trading-with-technical-analysis/learn/ -q 1080`

 I get the following:

```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\udemy\udemy-downloader-master\main.py", line 1939, in <module>
    pre_run()
  File "C:\Users\Admin\Downloads\udemy\udemy-downloader-master\main.py", line 269, in pre_run
    keys = json.loads(keyfile.read())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)
```

**Comment by Puyodead1** [comment]
you didnt follow the template of the keyfile.json

**Comment by rajhlinux** [comment]
I have two keys, I'm a little confused which key goes where...

**Comment by rajhlinux** [comment]
I also added a space between each key like the following:

`aaaa : bbbb`

is this correct?

**Comment by Puyodead1** [comment]
please, read the README, the section literally has a picture guide............. https://github.com/Puyodead1/udemy-downloader#key-id-and-key

**Comment by rajhlinux** [comment]
is "key" the actual decryption key?

**Comment by rajhlinux** [comment]
the key ID, has to be unique for all course videos and decryption key can be the same for all udemy videos?

**Comment by rajhlinux** [comment]
Just want to be clear,

There is a total of 72 videos that needs to be downloaded from a course, using "udemy-downloader", I need to obtain 72 different "key" and "key id"?

**Comment by Puyodead1** [comment]
no

**Comment by rajhlinux** [comment]
Alright, Thanks

**Comment by rajhlinux** [comment]
I put the Key ID on the left and Decrypt Key on the right... I still get the same error...

**Comment by Puyodead1** [comment]
because thats not the problem, you removed the "

**Comment by Puyodead1** [comment]
im not going to hold your hand, the information you need is in the readme file

**Comment by rajhlinux** [comment]
Alright so 

"aaaa" : "bbbb"

Will try this...

**Comment by rajhlinux** [comment]
Thank, now it seems like it is working now...

**Comment by rajhlinux** [comment]
I get this error:

```
C:\Users\Admin\Downloads\udemy\udemy-downloader-master>python main.py -c https://www.udemy.com/course/day-trading-strategies-day-trading-with-technical-analysis/learn/ -q 1080
[08:25:51] [udemy-downloader] [__init__:296] INFO: Login Success
[08:25:51] [udemy-downloader] [main:1661] INFO: > Fetching course information, this may take a minute...
[08:25:51] [udemy-downloader] [_subscribed_courses:619] CRITICAL: Udemy Says: 'latin-1' codec can't encode character '\u2026' in position 400: ordinal not in range(256) on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=day-trading-strategies-day-trading-with-technical-analysis
```

**Comment by Puyodead1** [comment]
> I get this error:
> 
> ```
> C:\Users\Admin\Downloads\udemy\udemy-downloader-master>python main.py -c https://www.udemy.com/course/day-trading-strategies-day-trading-with-technical-analysis/learn/ -q 1080
> [08:25:51] [udemy-downloader] [__init__:296] INFO: Login Success
> [08:25:51] [udemy-downloader] [main:1661] INFO: > Fetching course information, this may take a minute...
> [08:25:51] [udemy-downloader] [_subscribed_courses:619] CRITICAL: Udemy Says: 'latin-1' codec can't encode character '\u2026' in position 400: ordinal not in range(256) on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=day-trading-strategies-day-trading-with-technical-analysis
> ```

probably a duplicate of #94, If i remember correctly its related to an ellipsis unicode character (...). I havnt been able to fix this yet.

**Comment by rajhlinux** [comment]
Interesting... is this a "special" codec which Udemy uses which ffmpeg does not understand?

**Comment by Puyodead1** [comment]
no, its something from the course author i think. havnt done much looking into it but its not related to ffmpeg, its python

**Comment by rajhlinux** [comment]
it is possible to download all of the little chucks on the encrypted video files and decrypt all the little chunks of video?

I saw a tool called from "NirSoft" which can look up all the web cache, and I have found literally hundreds of tiny pieces of videos which are encrypted using NirSoft's ""VideoCacheView"... maybe writing a script to decrypt them all and stitch them using ffmpeg could do the trick?

**Comment by Puyodead1** [comment]
loooooool

**Comment by Puyodead1** [comment]
sure, you can do that if you want i guess. but thats killing a fly with a sledge hammer

**Comment by rajhlinux** [comment]
![a](https://user-images.githubusercontent.com/61344181/160218415-61961088-f3f3-4d34-889e-5972948c766d.jpg)

**Comment by Puyodead1** [comment]
you dont even need to look in the cache, you can get the dash manifest manually by looking in dev tools lmao

**Comment by Puyodead1** [comment]
if you feel like manually going through and downloading all 72 videos manually, go for it.

**Comment by rajhlinux** [comment]
> you dont even need to look in the cache, you can get the dash manifest manually by looking in dev tools lmao

Interesting, can you show a screen shot how I can obtain the "dash manifest"?

I need to know how I can obtain the right synchronized orders of little chucks of video...

seems like all of the videos are all scrambled...

**Comment by Puyodead1** [comment]
> maybe writing a script to decrypt them all and stitch them using ffmpeg could do the trick?
this tool already does that, i just haven't had the time to fix the codec issue which only happens with certain course

**Comment by Puyodead1** [comment]
> seems like all of the videos are all scrambled...

yeah, cause ur using a cache viewer

**Comment by Puyodead1** [comment]
well thats how the browser knows how to play it

**Comment by Puyodead1** [comment]
so yes

**Comment by rajhlinux** [comment]
Alright, I think a simple bash script or maybe even python script can download all the little chunks of video and decrypt them.

From this point on, we should have 100% decrypted little chunks of videos, only thing left is to stich them together in the proper order all at once using ffmpeg or even any video editor tool...

does not seem to hard to do...

**Comment by rajhlinux** [comment]
There are many tools from "bento" which can do most of the decrypting.

**Comment by Puyodead1** [comment]
> There are many tools from "bento" which can do most of the decrypting.

yes, and this tool used to use them, I switched because they had issues with non english characters

**Comment by rajhlinux** [comment]
> > There are many tools from "bento" which can do most of the decrypting.
> 
> yes, and this tool used to use them, I switched because they had issues with non english characters

Interesting...

How can I use your script to download all the encrypted videos in the proper sequence?
Is it possible to rename the little chunks of video like: "Video_1, Video_2, Video_3" and saved to a folder?

**Comment by Puyodead1** [comment]
okay, you clearly dont want to use the program how it was intended, this is really offtopic and I'm done entertaining this. do what you want, but I'm not going to teach you the basics of web streaming and DRM
