### ISSUE TITLE
[Help Request] can someone help me please

### ISSUE THREAD

**Issue by thisiswloq** [Puyodead1/udemy-downloader#115]
Hello everyone, as I can see it is apparently still being updated and therefore seems to be working. I've been here for several months and am trying to download my purchased course so far without success, I've tried other DRM downloaders etc. that didn't work because Udemy introduced their DRM protection, but with some bugs I see that people are successful and download their courses.
That's why I'm asking if someone could help me to set it up correctly for me, that would be super nice, thank you.
Could also write on Discord if someone should find each other.

I followed the description of the library as best as I could, but unfortunately I didn't have any success, I always got an error. I tried the same thing with Udeler but he could only download all preview videos (non-DRM).

**Comment by Puyodead1** [comment]
post the error

**Comment by thisiswloq** [comment]
it starts with the current WidevineCdm version that is available online that I found no longer works and therefore the keys for decrypting are not displayed to me.
4.10.2209.0-win-x64.zip

**Comment by Puyodead1** [comment]
yeah? that cdm was killed back in February as I said in the README 
> You can find information on downgrading the CDM version on the wiki, please note that CDM version 2209 is already revoked as of 12/5/2021 and no longer works on Udemy as of 2/1/2022. This information is just to have it available. 

As I also said in the README, I do not provide support for getting keys. that is not my problem.
