### ISSUE TITLE
Error in protobuf while invoking main.py

### ISSUE THREAD

**Issue by rvipinkumar** [Puyodead1/udemy-downloader#118]
Getting this error while using the code: 

Traceback (most recent call last):
  File "C:\ripper\main.py", line 22, in <module>
    from utils import extract_kid
  File "C:\ripper\utils.py", line 3, in <module>
    import widevine_pssh_pb2
  File "C:\ripper\widevine_pssh_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Python39\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Not sure what changed.

**Comment by rvipinkumar** [comment]
Python version is 3.9.4, if that makes any difference.

**Comment by Puyodead1** [comment]
Version 4 of protobuf has just been riddled with problems

pip uninstall protobuf
pip install protobuf==3.20

**Comment by rvipinkumar** [comment]
Just did that and it worked. Thank you! Closing the Issue.
