### ISSUE TITLE
Is there any way to obtain keys?

### ISSUE THREAD

**Issue by thornzz** [Puyodead1/udemy-downloader#119]
Hi,

I have read  "CDM version 2209 is already revoked as of 12/5/2021 and no longer works on Udemy as of 2/1/2022". So thats mean this tool not useful anymore if i havent got decrypt key for related course or is there any other way to get somehow to obtain this keys.? I wonder if there is a way to get keys i ll try to find a way somehow

**Comment by Puyodead1** [comment]
If the program was useless, I would have clearly said so in the README.

**Comment by espinella8** [comment]
In other words, this code is useless. It's surely not worth any donation.

**Comment by Puyodead1** [comment]
> In other words, this code is useless. It's surely not worth any donation.

Not at all. Hundreds of people are successfully using the program just fine. Your inability to research a little to find ways to get keys is not my problem :)
