### ISSUE TITLE
some courses videos are skipping

### ISSUE THREAD

**Issue by Ex-Communicad0** [Puyodead1/udemy-downloader#13]
some courses videos skipping like for this course you can check (if you have a business account or I can provide you token & course id you can check)

https://www.udemy.com/course/an-entire-mba-in-1-courseaward-winning-business-school-prof/
>> for this course, its downloading  1st video on every module and ignoring other videos :-(

https://www.udemy.com/course/ielts-band-7-preparation-course/
![Image](https://i.imgur.com/xz0MLcc.png)
>> for this course, in the middle after downloading half stuck with an error, maybe it's for resolution not found, but every course support at least 720P for all videos. in this case, you can apply a system, if given resolution not found in the videos, they can download at least the last available resolution on videos.
Note:- I am downloading 720p resolution

**Comment by Puyodead1** [comment]
> 
> 
> some courses videos skipping like for this course you can check (if you have a business account or I can provide you token & course id you can check)
> 
> https://www.udemy.com/course/an-entire-mba-in-1-courseaward-winning-business-school-prof/
> 
> > > for this course, its downloading  1st video on every module and ignoring other videos :-(
> 
> https://www.udemy.com/course/ielts-band-7-preparation-course/
> ![Image](https://camo.githubusercontent.com/529bb5a644afa36e96144eb88261239718d36a01afd6971b2aebe628cc05b2b1/68747470733a2f2f692e696d6775722e636f6d2f787a304d4c63632e706e67)
> 
> > > for this course, in the middle after downloading half stuck with an error, maybe it's for resolution not found, but every course support at least 720P for all videos. in this case, you can apply a system, if given resolution not found in the videos, they can download at least the last available resolution on videos.
> > > Note:- I am downloading 720p resolution

That's weird, can you send me your bearer token so I can investigate this? ``puyodead@protonmail.com``

**Comment by Puyodead1** [comment]
You may have sent me the wrong bearer token, because neither of those courses are showing in your subscribed courses list.

**Comment by Ex-Communicad0** [comment]
> You may have sent me the wrong bearer token, because neither of those courses are showing in your subscribed courses list.

ah sorry wait this is a business account I will provide next day all required details

**Comment by Ex-Communicad0** [comment]
Hello, after the latest update the issue is now fixed

**Comment by Puyodead1** [comment]
Good to hear :)
