### ISSUE TITLE
[Bug]: unable to install requirements from requirements.txt

### ISSUE THREAD

**Issue by chnaveen1993** [Puyodead1/udemy-downloader#136]
### What happened?

![image](https://user-images.githubusercontent.com/110925701/184527239-3526a1d2-02e5-4470-888a-b6dbec460b35.png)
  requirements.txt available in same directory, still python unable to install it

using python 3.10

### Expected Result

will install all requirements

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by rickeymandraque** [comment]
Hello,
 1) you have 2 "\\" in your path
 2) execute this in real console, not in visual studio code, the VSC console is isolated from the system in a way.
 3) execute in admin (not secure, i know) PowerShell or Windows PowerShell
```console
cd D:\UDL 
pip uninstall -r requirements.txt
pip install -r requirements.txt
exit
```
4) open console in you directory (D:\UDL according to your screenshot) in user (not admin) and execute
```console
python main.py [OPTIONS]
```

**Comment by Puyodead1** [comment]
the command is just wrong
