### ISSUE TITLE
filenotfound error for keyfile.name

### ISSUE THREAD

**Issue by ravYog99** [Puyodead1/udemy-downloader#14]
filenotfound error for keyfile.json

C:\Users\username\Downloads\udemy-downloader-master>py main.py
Traceback (most recent call last):
  File "C:\Users\username\Downloads\udemy-downloader-master\main.py", line 36, in <module>
    with open(keyfile_path, 'r') as keyfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Downloads\\udemy-downloader-master\\keyfile.json'

**Comment by Puyodead1** [comment]
you need to rename the keyfile.example.json to keyfile.json

**Comment by ravYog99** [comment]
I have already renamed it. check the path I provided.

**Comment by ravYog99** [comment]
Bro, also want to know.. How can I get the key. I researched alot but couldn't find it. It would be a great help.

**Comment by Puyodead1** [comment]
> 
> 
> I have already renamed it. check the path I provided.

The error is saying that it can't find the file

**Comment by Puyodead1** [comment]
> 
> 
> Bro, also want to know.. How can I get the key. I researched alot but couldn't find it. It would be a great help.

Please see #10

**Comment by ravYog99** [comment]
Thanks for your reply I check that post and installed it. But it isn't working on chrome ver. I use. Can you put some idea without naming the tool.

**Comment by Puyodead1** [comment]
> 
> 
> Thanks for your reply I check that post and installed it. But it isn't working on chrome ver. I use. Can you put some idea without naming the tool. I also tried using older v, but still no luck

You have to either use an old chrome version and stop it from updating or manually override the Widevine CDM files: https://github.com/WHTJEON/widevine_CDMPatch

**Comment by ravYog99** [comment]
Thanks man!! .. it worked like charm.
