### ISSUE TITLE
[Bug]: Starting videos downloading issue

### ISSUE THREAD

**Issue by CookJ77** [Puyodead1/udemy-downloader#140]
### What happened?

Non DRM Videos downloading in 720p format, Also sometimes some videos didn't decrypting / isn't downloading properly means unable to download some video fragments :sad

### Expected Result

cause i choose -q 1080 flag means every video should download in 1080p quality

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
As I said in discord, not a bug. Non drm videos are maxed out at 720z
