### ISSUE TITLE
[Bug]: Forbidden 403 Error for subscription

### ISSUE THREAD

**Issue by hacksonic** [Puyodead1/udemy-downloader#141]
### What happened?

Got the forbidden error(master branch), timeout(feat selenium) when i was trying to download scbscription course(personal plan). 

### Expected Result

Expected Result:  no error and can download subscription course. 

Master/main branch: 
![image](https://user-images.githubusercontent.com/112186974/194693961-98536124-634d-447c-a790-92850cc7f011.png)
![image](https://user-images.githubusercontent.com/112186974/194693994-ca070c0e-28da-41a3-b2c4-71565aba5e2a.png)

feat-selenium:
![image](https://user-images.githubusercontent.com/112186974/194694018-8cee47b7-ce61-40f4-ab2b-d103049b650f.png)

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
(UDDL) PS E:\Udemy\Tool\udemy-downloader-master> python .\main.py -c https://www.udemy.com/course/learn-website-hacking-penetration-testing-from-scratch/learn/ --download-assets
[02:39:17] [udemy-downloader] [__init__:287] INFO: Login Success
[02:39:17] [udemy-downloader] [main:1467] INFO: > Fetching course information, this may take a minute...
[02:39:18] [udemy-downloader] [_get:804] ERROR: Failed request https://www.udemy.com/course/learn-website-hacking-penetration-testing-from-scratch/learn/
[02:39:18] [udemy-downloader] [_get:805] ERROR: 403 Forbidden, retrying (attempt 0 )...
[02:39:19] [udemy-downloader] [_get:804] ERROR: Failed request https://www.udemy.com/course/learn-website-hacking-penetration-testing-from-scratch/learn/
[02:39:19] [udemy-downloader] [_get:805] ERROR: 403 Forbidden, retrying (attempt 1 )...
[02:39:21] [udemy-downloader] [_get:804] ERROR: Failed request https://www.udemy.com/course/learn-website-hacking-penetration-testing-from-scratch/learn/
[02:39:21] [udemy-downloader] [_get:805] ERROR: 403 Forbidden, retrying (attempt 2 )...
[02:39:22] [udemy-downloader] [_get:804] ERROR: Failed request https://www.udemy.com/course/learn-website-hacking-penetration-testing-from-scratch/learn/
[02:39:22] [udemy-downloader] [_get:805] ERROR: 403 Forbidden, retrying (attempt 3 )...
```

### Other information

![image](https://user-images.githubusercontent.com/112186974/194694257-c046f3b2-e919-45f4-aca9-873df7caa4f4.png)

**Comment by hacksonic** [comment]
for the non-subscription course, i can download via master branch. FYI

**Comment by Puyodead1** [comment]
Set headless to false in the config and try again and see where it gets stuck.

**Comment by hacksonic** [comment]
For subscription courses, will be stuck on the UD home page. (It seems that the selenium didn't catch and login successful)
But in the code, i got the login success message. 

[02:39:17] [udemy-downloader] [__init__:287] INFO: Login Success
[02:39:17] [udemy-downloader] [main:1467] INFO: > Fetching course information, this may take a minute...

![image](https://user-images.githubusercontent.com/112186974/194737648-3614c61e-994e-4fd1-9aed-139093b88ec6.png)

But for the non-subscription courses, can login and download sucessful. 

and no matter disable_ipv6 = True or False, the result is same.

**Comment by Puyodead1** [comment]
the login success message is useless honestly, in reality all it means is "i see you provided a bearer token". It should have been going to a login page. Can you check what the title of that page is? Selenium is waiting for it to equal something specific which is how it determines if the page is done loading.

**Comment by hacksonic** [comment]
Hi @Puyodead1 , thank for your patience at first. 

when i run the program, i will be lead to below page until timeout. 
![image](https://user-images.githubusercontent.com/112186974/194740853-1f2d74b6-eea8-4cf9-bbd5-f0a5d85ee54e.png)

Before the timeout error, I clicked to see what you call "login". It seems that the human verification page is stuck with the program.
Even if I pass verification by myself. The page just keeps reloading the page asks me to do it again. I think it's because of selenium.

![image](https://user-images.githubusercontent.com/112186974/194740939-14da3599-2f2c-4c22-a9bf-5aadbee78c6c.png)

any idea can fix this? 
thanks

**Comment by hacksonic** [comment]
hello @Puyodead1,  i've fixed by revising part of code.  thanks :)

**Comment by hacksonic** [comment]
hello @Puyodead1, i've fixed by revising part of code. thanks :)

**Comment by glyxerin3** [comment]
@hacksonic Can you tell me, what you find in the code and how you fixed it? I'm having the same issue and don't know how to fix.

**Comment by dokozweo** [comment]
I also have the same error, I'm using the udemy personal plan account, I'm using the Selenium brach

how to fix it? 
![Cuplikan layar 2022-12-02 070113](https://user-images.githubusercontent.com/11250709/205184721-45e6e3ce-8335-450b-8455-e8a866a873c7.png)

![Cuplikan layar 2022-12-02 070456](https://user-images.githubusercontent.com/11250709/205184855-2b058d9e-47af-46e1-b848-bd7bd09cbcbe.png)

**Comment by Puyodead1** [comment]
> hi @Puyodead1 I also have the same error, I'm using the udemy personal plan account, I'm using the Selenium brach
> 
> how to fix it? ![Cuplikan layar 2022-12-02 070113](https://user-images.githubusercontent.com/11250709/205184721-45e6e3ce-8335-450b-8455-e8a866a873c7.png)
> 
> ![Cuplikan layar 2022-12-02 070456](https://user-images.githubusercontent.com/11250709/205184855-2b058d9e-47af-46e1-b848-bd7bd09cbcbe.png)

you don't. those pages are designed to block automation tools, and bypassing them is extremely difficult.

**Comment by reteps** [comment]
I also have the same error :/
