### ISSUE TITLE
[Bug]:  skipped 1/283 lectures 

### ISSUE THREAD

**Issue by d6dash37** [Puyodead1/udemy-downloader#144]
### What happened?

Return code from the downloader was non-0 (error), skipping!

### Expected Result

expected to download all lectures/assets

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Other information

command used:

`python main.py -c https://www.udemy.com/course/complete-csharp-masterclass/learn/lecture/27277708?start=0#overview --id-as-course-name --download-assets --disable-ipv6 --log-level DEBUG
`

**Comment by nakacend** [comment]
[screenshot](https://i.imgur.com/9sepSC0.jpeg)

**Comment by Puyodead1** [comment]
Yt-sop failed to download the mpd. Nothing I can do about it
