### ISSUE TITLE
[Bug]: error downloading lectures

### ISSUE THREAD

**Issue by Zeddex** [Puyodead1/udemy-downloader#145]
### What happened?

I'm trying to download this course https://www.udemy.com/course/blockchain-developer/learn/
Get an error on 3rd lecture which has drm protection, but I have valid keys in keyfile.json

### Expected Result

Download all lectures

### Branch

master/main

### Relevant log output

```shell
[process_lecture:1225] INFO:       > Lecture '003 Course Structure - So You Get The Most Out Of It' has DRM, attempting to download
[udemy-downloader] [handle_segments:1038] INFO: > Downloading Lecture Tracks...
Traceback (most recent call last):
  File "D:\udemy-downloader\main.py", line 1700, in <module>
    main()
  File "D:\udemy-downloader\main.py", line 1693, in main
    parse_new(_udemy)
  File "D:\udemy-downloader\main.py", line 1316, in parse_new
    process_lecture(lecture, lecture_path, lecture_file_name, chapter_dir)
  File "D:\udemy-downloader\main.py", line 1226, in process_lecture
    handle_segments(source.get("download_url"), source.get("format_id"), lecture_title, lecture_path, lecture_file_name, chapter_dir)
  File "D:\udemy-downloader\main.py", line 1059, in handle_segments
    process = subprocess.Popen(args)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Puyodead1** [comment]
You didn’t install all the requirements, ytdlp is missing

**Comment by Zeddex** [comment]
$ pip install yt-dlp
Requirement already satisfied: yt-dlp in c:\python310\lib\site-packages (2022.6.29)
Requirement already satisfied: brotli in c:\python310\lib\site-packages (from yt-dlp) (1.0.9)
Requirement already satisfied: mutagen in c:\python310\lib\site-packages (from yt-dlp) (1.45.1)
Requirement already satisfied: websockets in c:\python310\lib\site-packages (from yt-dlp) (10.3)
Requirement already satisfied: pycryptodomex in c:\python310\lib\site-packages (from yt-dlp) (3.15.0)
Requirement already satisfied: certifi in c:\python310\lib\site-packages (from yt-dlp) (2022.6.15)

yt-dlp was installed before. Still have the same error.

**Comment by Zeddex** [comment]
> You didn’t install all the requirements, ytdlp is missing

yt-dlp was installed before. Still have the same error.

$ pip install yt-dlp
Requirement already satisfied: yt-dlp in c:\python310\lib\site-packages (2022.6.29)
Requirement already satisfied: brotli in c:\python310\lib\site-packages (from yt-dlp) (1.0.9)
Requirement already satisfied: mutagen in c:\python310\lib\site-packages (from yt-dlp) (1.45.1)
Requirement already satisfied: websockets in c:\python310\lib\site-packages (from yt-dlp) (10.3)
Requirement already satisfied: pycryptodomex in c:\python310\lib\site-packages (from yt-dlp) (3.15.0)
Requirement already satisfied: certifi in c:\python310\lib\site-packages (from yt-dlp) (2022.6.15)

**Comment by Puyodead1** [comment]
> > You didn’t install all the requirements, ytdlp is missing
> 
> 
> 
> yt-dlp was installed before. Still have the same error.
> 
> 
> 
> $ pip install yt-dlp
> 
> Requirement already satisfied: yt-dlp in c:\python310\lib\site-packages (2022.6.29)
> 
> Requirement already satisfied: brotli in c:\python310\lib\site-packages (from yt-dlp) (1.0.9)
> 
> Requirement already satisfied: mutagen in c:\python310\lib\site-packages (from yt-dlp) (1.45.1)
> 
> Requirement already satisfied: websockets in c:\python310\lib\site-packages (from yt-dlp) (10.3)
> 
> Requirement already satisfied: pycryptodomex in c:\python310\lib\site-packages (from yt-dlp) (3.15.0)
> 
> Requirement already satisfied: certifi in c:\python310\lib\site-packages (from yt-dlp) (2022.6.15)
> 
> 

You might have multiple python versions installed and pip is using a different one, or the scripts folder isn't in your path. Either way the script can't find ytdlp because it's not executable from the command line
