### ISSUE TITLE
[Feature Request]: Skip key for non-DRM courses

### ISSUE THREAD

**Issue by thesyntaxinator** [Puyodead1/udemy-downloader#151]
### Is your feature request related to a problem?

- [X] Yes
- [ ] No

### If yes, please describe

It would be ideal to not have to specify a key to download non-DRM courses.

### Describe the solution you'd like

See above

### Describe alternatives you've considered

See above

**Comment by Puyodead1** [comment]
added to master and feat/cookies branches. keyfile is no longer required and will print a warning to the screen.
