### ISSUE TITLE
[Feature Request]:  Merge request from Develop branch to Master branch to --use-h265 feature with latest fixes

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#154]
### Is your feature request related to a problem?

- [ ] Yes
- [X] No

### If yes, please describe

Few years back you gave video encoding support (like --use-h265) while downloading coerces, but those features are limited to in develop branch and that branch is too old and now, also those features are not available in master branch.

So, request to make those features available in master branch.

### Describe the solution you'd like

Pull request may be required. from develop to Master branch.

### Describe alternatives you've considered

NA

**Comment by Puyodead1** [comment]
added to both master and feat/cookies branches. along with some fixes and NVIDIA HEVC support
