### ISSUE TITLE
[Bug]: not merge mp4 m4a

### ISSUE THREAD

**Issue by mahnotz** [Puyodead1/udemy-downloader#156]
### What happened?

hi
not merge mp4 and m4a 
and encrypt decrypt
output like this:

001 Overview.decrypted.m4a
001 Overview.decrypted.mp4
001 Overview.encrypted.m4a
001 Overview.encrypted.mp4

whats is problem?

i used branch feat/cookies

### Expected Result

merge mp4 and one file

### Branch

Other (Enter below)

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
You don’t have decryption keys

**Comment by mahnotz** [comment]
i have keys,
decrypt works 
but not merge

**Comment by Puyodead1** [comment]
> i have keys, decrypt works but not merge

ok, well I can't magically tell you why it's not working for you.

**Comment by mahnotz** [comment]
Sorry, I checked this with shaka-packager and it was done and there was no problem,

**Comment by mahnotz** [comment]
I changed this hvc1 to this avc1
And now it works
