### ISSUE TITLE
[Bug]: not encrypt one chapter

### ISSUE THREAD

**Issue by mahnotz** [Puyodead1/udemy-downloader#158]
### What happened?

hi
just this one chapter can not decrypt:
"013 Throw It Away If You can Replace it for X$ or Less.encrypted.m4a"

### Expected Result

decrypt this

### Branch

master/main

**Comment by Puyodead1** [comment]
what the fuck do you expect me to do? you've given no useful information.

**Comment by mahnotz** [comment]
sorry

this line append
in main.py
file_name = file_name.replace("$", "")
