### ISSUE TITLE
[Feature Request]: use selenium with yt-dlp

### ISSUE THREAD

**Issue by mahnotz** [Puyodead1/udemy-downloader#159]
### Is your feature request related to a problem?

- [X] Yes
- [ ] No

### If yes, please describe

https://github.com/Puyodead1/udemy-downloader/issues/63

yt-dlp error 403 for udemy subs

### Describe the solution you'd like

is it possible use selenium with yt-dlp to get info?

To get the information that yt-dlp is used to bypass captcha, Selenium is used

### Describe alternatives you've considered

selenium  with yt-dlp

**Comment by Puyodead1** [comment]
no
