### ISSUE TITLE
Problem adding access_token

### ISSUE THREAD

**Issue by srDesho2** [Puyodead1/udemy-downloader#163]
### What happened?

I'm using the command: 
python main.py -c UDEMY_URL -b tokken.txt 
to add my token, and I've this problem.

![problem](https://github.com/Puyodead1/udemy-downloader/assets/110626600/b69afcba-8702-4cb0-8da8-48a49d821b0f)

I have already re-login to my Udemy account, I have tried with several tokens and I get the same error.

They are purchased courses, I don't have a personal account or subscription.
The same thing happens to me with all purchased courses.
Please Help!!

### Expected Result

.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
`tokken.txt` is not a valid bearer token. nowhere in the README does it say that -b loads a text file...
