### ISSUE TITLE
AbstractCommand.cc:312

### ISSUE THREAD

**Issue by srDesho** [Puyodead1/udemy-downloader#164]
### What happened?

I get this error when I try to download any of the courses that I have purchased.
I don't know what could be wrong, I have already tried with firefox and chrome, also with different tokens but I get the same problem.

It shows me the following error and goes in an infinite loop:

06/05 15:06:31 [ERROR] CUID#7 - Download aborted. URI=https://hls-b.udemycdn.com/2020-07-19_03-08-10-b7bf6661f4b434ebda9f69cc4e85c7ae/2/hls/AVC_1920x1080_1200k_AAC-HE_64k/aa00693f5399cc95a11513b4d16c67b114d30.ts?secure=AoPcnQgIfs5lUnpqZ6trkQ%3D%3D%2C1686007987
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:Unknown socket error 10051 (0x2743)

06/05 15:06:31 [ERROR] CUID#8 - Download aborted. URI=https://hls-b.udemycdn.com/2020-07-19_03-08-10-b7bf6661f4b434ebda9f69cc4e85c7ae/2/hls/AVC_1920x1080_1200k_AAC-HE_64k/aa00693f5399cc95a11513b4d16c67b114d31.ts?secure=9vZxgHQ28_aguB9j3y5lYA%3D%3D%2C1686007987
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:Unknown socket error 10051 (0x2743)

### Expected Result

Download a course.

### Branch

master/main

### Relevant log output

06/05 15:06:31 [ERROR] CUID#7 - Download aborted. URI=https://hls-b.udemycdn.com/2020-07-19_03-08-10-b7bf6661f4b434ebda9f69cc4e85c7ae/2/hls/AVC_1920x1080_1200k_AAC-HE_64k/aa00693f5399cc95a11513b4d16c67b114d30.ts?secure=AoPcnQgIfs5lUnpqZ6trkQ%3D%3D%2C1686007987
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:Unknown socket error 10051 (0x2743)

06/05 15:06:31 [ERROR] CUID#8 - Download aborted. URI=https://hls-b.udemycdn.com/2020-07-19_03-08-10-b7bf6661f4b434ebda9f69cc4e85c7ae/2/hls/AVC_1920x1080_1200k_AAC-HE_64k/aa00693f5399cc95a11513b4d16c67b114d31.ts?secure=9vZxgHQ28_aguB9j3y5lYA%3D%3D%2C1686007987
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:Unknown socket error 10051 (0x2743)

### Other information

![problem](https://github.com/Puyodead1/udemy-downloader/assets/110246832/1a69d3a6-8a34-4bf2-9a63-78009f3ea5be)

**Comment by fazlulShanto** [comment]
try with `--disable-ipv6` option.
