### ISSUE TITLE
Could you provide videos from the beggining until the udemy videos was downloaded? I took 2 days full not yet downloaded one videos..[Feature Request]: 

### ISSUE THREAD

**Issue by Cookiemasters12** [Puyodead1/udemy-downloader#169]
### Is your feature request related to a problem?

- [X] Yes
- [ ] No

### If yes, please describe

Could you provide videos from the beggining until the udemy videos was downloaded? I took 2 days full not yet downloaded one videos..[Feature Request]: 

### Describe the solution you'd like

Could you provide videos from the beggining until the udemy videos was downloaded? I took 2 days full not yet downloaded one videos..[Feature Request]: 

### Describe alternatives you've considered

Could you provide videos from the beggining until the udemy videos was downloaded? I took 2 days full not yet downloaded one videos..[Feature Request]: 

### Additional context

Could you provide videos from the beggining until the udemy videos was downloaded? I took 2 days full not yet downloaded one videos..[Feature Request]:

**Comment by Puyodead1** [comment]
Invalid
