### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [Puyodead1/udemy-downloader#176]
![230813-021850](https://github.com/Puyodead1/udemy-downloader/assets/52028866/7442a81c-4813-4fb0-815a-6d6dd016c180)

Hi, im getting this error when running main.py.
Not sure if its script bug or config error. More info can be provided if need.

**Comment by Puyodead1** [comment]
Please use the --save-to-file option and after the error, please DM me the saved/course_content.json file on discord so I can look.

**Comment by Puyodead1** [comment]
Please pull the latest changes and try.

**Comment by Puyodead1** [comment]
> Hi, the new change fixed the error, but there seems to be a new issue (not sure if its related to the change). The script would finish without downloading lectures from the last chapter, the folder is created though, just empty. And the first two chapter folders are having the same 01 index.
> 
> ![image](https://user-images.githubusercontent.com/52028866/260283707-a1347495-5610-40f3-b90f-02ead4323953.png)

I'll take a look tomorrow (its 2am for me atm)

**Comment by Puyodead1** [comment]
> So I tried another course (one that doesn't have "lectures without chapter" as u mentioned in the [e9b9d8a](https://github.com/Puyodead1/udemy-downloader/commit/e9b9d8a6a471992f2b176cf01845e12bcda47548) commit) after all your recent changes, but the problem still exists - the last chapter folder is empty without any lectures.
> 
> Not a big issue but if you are willing to investigate, i can provide additonal info/log if u need (through discord or here).

Alright, this issue should be resolved now on the latest commit.

**Comment by Puyodead1** [comment]
> > Alright, this issue should be resolved now on the latest commit.
> 
> Indeed. Tried it again on my 1st course, no error and no missing chapter anymore. Thanks man, appreciate your efforts.
> 
> Also great to learn about this [yt-dlp](https://github.com/yt-dlp/yt-dlp/) tool through your project. Just fyi, cause I saw this on their doc:
> 
> > There are bugs in ffmpeg that causes various issues when used alongside yt-dlp. Since ffmpeg is such an important dependency, we provide custom builds with patches for some of these issues at [yt-dlp/FFmpeg-Builds](https://github.com/yt-dlp/FFmpeg-Builds).
> 
> They fixed things like long path support, and are actively maintaining it. Not sure if you would recommend using their version of ffmpeg as dependency on your project too.

ah cool, I didnt know that, thanks for letting me know. I would probably say that its recommended to use that build but not required.
