### ISSUE TITLE
Decrypt, key not found 

### ISSUE THREAD

**Issue by gersooonn** [Puyodead1/udemy-downloader#179]
![image](https://github.com/Puyodead1/udemy-downloader/assets/128495179/51194153-a41a-403b-8bef-06af7be8b539)

My keys are correct, I can only decrypt video by video, but it keeps showing keys not found, I edited the name to keyfile.json 
![image](https://github.com/Puyodead1/udemy-downloader/assets/128495179/37d57ed4-330f-45e9-9349-d14190fc82ad)
.
Still showing key not found, what to do?
Shaka-package is installed shaka-packager version v2.6.1-634af65-release.

**Comment by Puyodead1** [comment]
That is not how you fill in the file..... replace KeyID with the key id

**Comment by gersooonn** [comment]
@Puyodead1 Thank you very much for your attention! I finally got it.
Try to put an example template, how to fill in Read.me. It can make it easier for other people, layman like me.

**Comment by Puyodead1** [comment]
> > ![image](https://user-images.githubusercontent.com/128495179/265115687-51194153-a41a-403b-8bef-06af7be8b539.png)
> > My keys are correct, I can only decrypt video by video, but it keeps showing keys not found, I edited the name to keyfile.json ![image](https://user-images.githubusercontent.com/128495179/265125717-37d57ed4-330f-45e9-9349-d14190fc82ad.png) . Still showing key not found, what to do? Shaka-package is installed shaka-packager version v2.6.1-634af65-release.
> 
> Hi @gersooonn, Can you share a secret on how to get a key ID and key? I have read a couple of threads all refer to the old widevine-l3-decryptor plugin which does not work now. So would appreciate some hints or instructions. Thanks

no
