### ISSUE TITLE
Error on fetching courses

### ISSUE THREAD

**Issue by atakurt034** [Puyodead1/udemy-downloader#18]
Fetching Course data, this may take a minute...
An error occurred while trying to fetch the course data! <html><script async src='/cdn-cgi/bm/cv/669835187/api.js'></script><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
<script type="text/javascript">(function(){window['__CF$cv$params']={r:'655ae886ab340a8c',m:'5001597e4bb7d8d50da696aa8339476dd63c7729-1622073074-1800-AXbWxGbaFMeSAV/uxr5JKU5lbn4PUpeIXjW+TdGXaHYPz7pnxG57wKiJuhXayDd5G5RE2qrPuEwTose7SXizpj9I3M1CWttGEfBGTAKEBSqzCgsSUa3bcZwB/0xEAqbFWnd//39qiDoHrRV84xwLpb97Ehe2HtriVntam+KUP0biL3jeoqR3z4CKSWit38crXcSwhyVeU75TSBMh4dxGrwARh5eNTN4baf/F6VjqYZ24r8dErn5bHCLgmep7mf76S2u6mfoV9l9gRXNV5bZdVMpP9MJw7AvtYbi4bVGQ/Hfgbb94hDGW2zU91VTr3DBdVXh/gErbMT86l9vZpPJcLuOjklSLZ9matcDGt+Riz/lGyUSN40iYOiYmWw2HZ5TjB4VNI3icRi+nFZcKbPYXN9ctzQB4mZdURKYT7n5lxokOnT5siOqhMbMGnSan7zJqAuMi8Tg40GFxU12UvkJDPY3XFCs6XsoL8EUkIIDZhMEFZhKtkuLr2WWCvNmm3Tr7NbJabxxFZTPxtSw76SS0y3lGxWYknW/8bguRQ7sAiGvi5w4f108P44zlI1CPDT1wRir0pyodh6+bnOikxSJS+AumpbuUKAF/MjOAwyy+YTOKmE9R3WtNANN+ztR22vjpyg==',s:[0xc5e4e94200,0x334e7a8097],}})();</script></body></html>

**Comment by atakurt034** [comment]
etching Course data, this may take a minute...
An error occurred while trying to fetch the course data! {
    "error": {
        "status_code": 504,
        "message": "Sorry. We are having trouble reaching our servers. Try waiting a minute or two and then reload."
    }
}

this one occurs on large courses

**Comment by Puyodead1** [comment]
Both of these errors are caused by the course being large, I'm working on an update that will fix this issue. I'll update this issue when it's done.

**Comment by atakurt034** [comment]
> Both of these errors are caused by the course being large, I'm working on an update that will fix this issue. I'll update this issue when it's done.

Ok thanks. Been trying to download all of my courses before the end of the month before the DRM updates.

**Comment by Puyodead1** [comment]
> > Both of these errors are caused by the course being large, I'm working on an update that will fix this issue. I'll update this issue when it's done.
> 
> Ok thanks. Been trying to download all of my courses before the end of the month before the DRM updates.

I totally understand! Something I'm going to put in the read me also is that once you have the keys, you shouldn't have to worry about getting them again, so when the CDM updates, the keys should still be valid. (Unless udemy realizes the problem with that and changes it lol)

**Comment by bydioeds** [comment]
Was this implemented in the selenium branch? 

![Captura de pantalla_2023-05-11_20-24-53](https://github.com/Puyodead1/udemy-downloader/assets/8415008/e31ba715-a9d4-4434-af3c-6541c2938e2f)
