### ISSUE TITLE
[Bug]: ARIA2C IS MISSING FROM YOUR SYSTEM OF PATH

### ISSUE THREAD

**Issue by pauloandriola** [Puyodead1/udemy-downloader#181]
### What happened?

Every time I try to use the software, this error appears to me "ARIA2C IS MISSING FROM YOUR SYSTEM OF PATH"
I don't know where to install this thing called aria2c.

![image](https://github.com/Puyodead1/udemy-downloader/assets/25313049/b251a5e7-1d58-4163-a6f6-5fb6e4271163)

### Expected Result

 hope you can help me with the solution for this installation; my system is Windows 10

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
this is not a bug. you just didnt install it correctly, as the instructions say, you must be able to run aria2c from the command prompt. this is something that can be solved with google.
