### ISSUE TITLE
[Bug]: --download-assets ignores .py resources

### ISSUE THREAD

**Issue by Foxtrod89** [Puyodead1/udemy-downloader#183]
### What happened?

**python3** main.py **-c** COURSE_URL **--download-assets --skip-lectures** couldn't detect *.py related resources. 

### Expected Result

**find** [COURSE_PATH] **-type f -iname "*.py"** - should fetch .py files but output is empty

### Branch

master/main

### What operating systems are you seeing the problem on?

MacOS

### Relevant log output

```shell
https://pastebin.com/Yp6cQ6aG
```

### Other information

conda env
Python 3.8.17
macOS BigSur 11.6

example
<img width="1073" alt="Screen Shot 2023-09-22 at 12 34 02 PM" src="https://github.com/Puyodead1/udemy-downloader/assets/19302114/6af3d4cb-7300-4c1d-bd9a-8428222e3f7d">

**Comment by Puyodead1** [comment]
theres nothing here that I can work with. upload _udemy.json file

**Comment by Foxtrod89** [comment]
I don't have **_udemy.json**

**Comment by Puyodead1** [comment]
> I don't have **_udemy.json**

--save-to-file

**Comment by Foxtrod89** [comment]
> > I don't have **_udemy.json**
> 
> --save-to-file

https://pastebin.com/C65SVi4R

**Comment by Puyodead1** [comment]
> > > I don't have **_udemy.json**
> > 
> > 
> > --save-to-file
> 
> https://pastebin.com/C65SVi4R

would you be able to contact me either on discord or email?

**Comment by Puyodead1** [comment]
resolved in a461f5fc8628603962b1a0733c0c55ff0da7e3d5
