### ISSUE TITLE
[Bug]: Cannot load extension with file or directory name _version.py. Filenames starting with "_" are reserved for use by the system ;  Could not load manifest.

### ISSUE THREAD

**Issue by Marietto2008** [Puyodead1/udemy-downloader#184]
### What happened?

Hello.

I'm using Ubuntu 23.04 and Chrome Version 117.0.5938.92 (Official Build) (64-bit). I'm trying to load your extension,but I see two different errors :

Error 1 :

Cannot load extension with file or directory name _version.py. Filenames starting with "_" are reserved for use by the system. 

Error 2 : Could not load manifest.

How to fix them ? 

### Expected Result

That it has been able to load correctly.

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

### Relevant log output

```shell
Cannot load extension with file or directory name _version.py. Filenames starting with "_" are reserved for use by the system ;  Could not load manifest.
```

**Comment by Puyodead1** [comment]
What the fuck.... this isn't a chrome extension....
