### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by javadovrufiq99** [Puyodead1/udemy-downloader#189]
Which Python version needs to be installed to use the project?

You didn't explain it.

**Comment by Puyodead1** [comment]
3

**Comment by javadovrufiq99** [comment]
I have no idea in which version the program was coded, because you are the one who coded the program, not me, that's why I say it.

**Comment by Puyodead1** [comment]
> I have no idea in which version the program was coded, because you are the one who coded the program, not me, that's why I say it.

and I told you..?

I said I dont know the min version it can run, as I usually use newer version like 3.11 and soon 3.12

**Comment by javadovrufiq99** [comment]
I will install 3.11 okay. Thanks for replying.
