### ISSUE TITLE
Python dependency issues

### ISSUE THREAD

**Issue by asdfmonster261** [Puyodead1/udemy-downloader#19]
Ubuntu 20.04
Python 3.8.5

bitfield won't try to install until cython is first installed.

after running `pip install cython` the bitfield installation gives a pretty large wall of text in an error

tried running as both root and non roott
https://pastebin.com/hVQ9bvZM

**Comment by Puyodead1** [comment]
bitfield isn't required anymore, guess I didn't realize that. the program should run without installing it.
