### ISSUE TITLE
[Feature Request]: More a question... does it work for Udemy Business?

### ISSUE THREAD

**Issue by giuseppe-salvatore** [Puyodead1/udemy-downloader#191]
### Is your feature request related to a problem?

- [ ] Yes
- [X] No

### Describe the solution you'd like

In the old days I was using Udeler, it had support also for Udemy Business as it's essentially the same streaming platform, just uses a different way to authenticate and charge companies rather than individuals.

It would be nice to see this but I understand it might require effort

### Describe alternatives you've considered

None as I didn't see anything else other than Udeler, which stopped working a while ago :(

**Comment by Puyodead1** [comment]
yes... you could just try it
