### ISSUE TITLE
m4a file

### ISSUE THREAD

**Issue by lbarria77** [Puyodead1/udemy-downloader#193]
### What happened?

Hello, how are you, does anyone know why some videos save two files, one with the extension m4a and mp4, but they do not work, they are saved with the file name.encrypted.m4a and the same for the mp4

### Expected Result

To see the videos

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
`encrypted.mp4` is encrypted video, `encrypted.m4a` is encrypted audio. ofc it "wont work" correctly if you dont setup decryption, read the README file.
