### ISSUE TITLE
Some Videos are missing with extension name: encrypted.mp4.part.frag.urls

### ISSUE THREAD

**Issue by parvinders347** [Puyodead1/udemy-downloader#198]
Hi, Puyo
Some videos are not downloading or merging

Instead of that video, it is coming as mp4 and mpa file.
Like this:-
Examplevideo.encrypted.mp4.part.frag.urls

What's the issue?
![image](https://github.com/Puyodead1/udemy-downloader/assets/53009524/e815400d-e3c1-4b6d-8c63-3c4ee17b40f5)

**Comment by Puyodead1** [comment]
file name too long

**Comment by parvinders347** [comment]
Okay thanks is there any command that i can download specific lectures? I also tried to find it in the previous question answer but I couldn't find it

**Comment by Puyodead1** [comment]
> Okay thanks is there any command that i can download specific lectures? I also tried to find it in the previous question answer but I couldn't find it

Because it doesn't exist

**Comment by parvinders347** [comment]
I have found the solution I tried --id-as-course-name

**Comment by hughware** [comment]
> I have found the solution I tried --id-as-course-name

how to do it?

**Comment by hughware** [comment]
> I have found the solution I tried --id-as-course-name

show code
