### ISSUE TITLE
[Bug]:  Access token no longer works

### ISSUE THREAD

**Issue by hojunior** [Puyodead1/udemy-downloader#199]
### What happened?

Hello good afternoon!

Sorry, I'm using Google Translate, so something may be incomprehensible.

I used to download videos from Udemy, with the access token stored in the .env file, now Udemy has changed the course access token to a length apparently twice what it was before, since then I have not been able to download it.

I used the following command:

python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG

It always worked, but not anymore.

I would like to know how I can download using browser cookies, what exactly would I need?

Could you please structure, as an example, what the command line would look like so that I understand better?

### Expected Result

Download videos from Udemy

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
[06:39:05] [udemy-downloader] [pre_run:331] INFO: Output directory set to C:\path\Puyodead3\udemy-downloader-master\out_dir
[06:39:05] [udemy-downloader] [main:1934] INFO: > Fetching course information, this may take a minute...
[06:39:06] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:06] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 0 )...
[06:39:07] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:07] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 1 )...
[06:39:08] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:08] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 2 )...
[06:39:09] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:09] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 3 )...
[06:39:11] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:11] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 4 )...
[06:39:12] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:12] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 5 )...
[06:39:13] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:13] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 6 )...
[06:39:14] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:14] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 7 )...
[06:39:15] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:15] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 8 )...
[06:39:16] [udemy-downloader] [_get:1109] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
[06:39:16] [udemy-downloader] [_get:1110] ERROR: 403 Forbidden, retrying (attempt 9 )...
[06:39:17] [udemy-downloader] [_subscribed_courses:736] CRITICAL: Udemy Says: 'NoneType' object has no attribute 'content' on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=fundamentos-de-ethical-hacking
```

### Other information

Windows 11 - Chrome browser

![image](https://github.com/Puyodead1/udemy-downloader/assets/123262211/d16bfb29-e13c-4377-baa5-533b1251afe9)

**Comment by Puyodead1** [comment]
Then use cookies or the -b option...

**Comment by hojunior** [comment]
Yes, I need help using cookies, any instructions?

**Comment by Puyodead1** [comment]
> > Then use cookies or the -b option...
> 
> Yes, I need help using cookies, any instructions?

literally in the readme

**Comment by hojunior** [comment]
> > > Then use cookies or the -b option...
> > 
> > 
> > Yes, I need help using cookies, any instructions?
> 
> literally in the readme

Thanks, I'll check it out soon!

**Comment by hojunior** [comment]
> python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG

What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.

I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.

You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.

Could you structure the command for me, something like how I used it and how it should be for cookies?

Here's how I've always used it:

python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG

Could you kindly write what the new command would look like so I can copy and paste it into main.py?

If I can't, I'll understand, but I would be immensely grateful if you could help.

**Comment by Puyodead1** [comment]
> > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> 
> I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> 
> You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> 
> Could you structure the command for me, something like how I used it and how it should be for cookies?
> 
> Here's how I've always used it:
> 
> python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> 
> If I can't, I'll understand, but I would be immensely grateful if you could help.

no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.

**Comment by hojunior** [comment]
> > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > 
> > 
> > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> > Could you structure the command for me, something like how I used it and how it should be for cookies?
> > Here's how I've always used it:
> > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> > If I can't, I'll understand, but I would be immensely grateful if you could help.
> 
> no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> 
> theres a difference between helping and plain hand holding
> 
> https://github.com/Puyodead1/udemy-downloader#cookies

All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command --brow chrome and --browser chrome--os-course-name, I don't know where I Insero is the cause of the error or if I have something else wrong with the script.

This way it seems more logical to me:
python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG

I will continue trying here, anyway, thank you!

**Comment by Puyodead1** [comment]
> > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > 
> > > 
> > > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> > > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> > > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> > > Could you structure the command for me, something like how I used it and how it should be for cookies?
> > > Here's how I've always used it:
> > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> > > If I can't, I'll understand, but I would be immensely grateful if you could help.
> > 
> > 
> > no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> > theres a difference between helping and plain hand holding
> > https://github.com/Puyodead1/udemy-downloader#cookies
> 
> All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command **--browser chrome and --browser chrome --id-as-course-name**, I don't know where I put it is the cause of the error or if I have something else wrong with the script.
> 
> This way it seems more logical to me: python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> I will continue trying here, anyway, thank you!

then you should have said what you had tried, anyways your command is correct, make sure you are logged into udemy in chrome, and then close chrome before running the command. if you have errors, post them

**Comment by jkfhto** [comment]
> > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > 
> > > 
> > > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> > > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> > > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> > > Could you structure the command for me, something like how I used it and how it should be for cookies?
> > > Here's how I've always used it:
> > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> > > If I can't, I'll understand, but I would be immensely grateful if you could help.
> > 
> > 
> > no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> > theres a difference between helping and plain hand holding
> > https://github.com/Puyodead1/udemy-downloader#cookies
> 
> All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command **--browser chrome and --browser chrome --id-as-course-name**, I don't know where I put it is the cause of the error or if I have something else wrong with the script.
> 
> This way it seems more logical to me: python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> I will continue trying here, anyway, thank you!

Have you found a solution to the same problem?

**Comment by Puyodead1** [comment]
> > > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> > > > > 
> 
> > > > > 
> 
> > > > > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> 
> > > > > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> 
> > > > > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> 
> > > > > Could you structure the command for me, something like how I used it and how it should be for cookies?
> 
> > > > > Here's how I've always used it:
> 
> > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> > > > > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> 
> > > > > If I can't, I'll understand, but I would be immensely grateful if you could help.
> 
> > > > 
> 
> > > > 
> 
> > > > no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> 
> > > > theres a difference between helping and plain hand holding
> 
> > > > https://github.com/Puyodead1/udemy-downloader#cookies
> 
> > > 
> 
> > > 
> 
> > > All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command **--browser chrome and --browser chrome --id-as-course-name**, I don't know where I put it is the cause of the error or if I have something else wrong with the script.
> 
> > > This way it seems more logical to me: python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> 
> > > I will continue trying here, anyway, thank you!
> 
> > 
> 
> > Have you found a solution to the same problem?
> 
> 
> 
> I still haven't been able to get it to work.

Well you're not going to get help when you don't even say what the problem is.

**Comment by hojunior** [comment]
> > > > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> > 
> > 
> > > > > > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> > 
> > 
> > > > > > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> > 
> > 
> > > > > > Could you structure the command for me, something like how I used it and how it should be for cookies?
> > 
> > 
> > > > > > Here's how I've always used it:
> > 
> > 
> > > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > 
> > 
> > > > > > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> > 
> > 
> > > > > > If I can't, I'll understand, but I would be immensely grateful if you could help.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> > 
> > 
> > > > > theres a difference between helping and plain hand holding
> > 
> > 
> > > > > https://github.com/Puyodead1/udemy-downloader#cookies
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command **--browser chrome and --browser chrome --id-as-course-name**, I don't know where I put it is the cause of the error or if I have something else wrong with the script.
> > 
> > 
> > > > This way it seems more logical to me: python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > 
> > 
> > > > I will continue trying here, anyway, thank you!
> > 
> > 
> > > 
> > 
> > 
> > > Have you found a solution to the same problem?
> > 
> > 
> > I still haven't been able to get it to work.
> 
> Well you're not going to get help when you don't even say what the problem is.

I'm leaving it to try again during this weekend, when I'll have more time, so I can tell you all the problems that occur here.

**Comment by jkfhto** [comment]
> > > > > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > What may be intuitive for many, is not very easy for me, I'm not in the programming field and I'm not very familiar with the subject.
> > > 
> > > 
> > > > > > > I'm sorry to bother you with this issue, but I felt comfortable asking for help because you offered it on your Github Udemy Downloader page.
> > > 
> > > 
> > > > > > > You took the time to read my problem report and yes you helped by answering my questions, for that I am very grateful and even for the downloader, but unfortunately I can't move forward, I had already read the readme.
> > > 
> > > 
> > > > > > > Could you structure the command for me, something like how I used it and how it should be for cookies?
> > > 
> > > 
> > > > > > > Here's how I've always used it:
> > > 
> > > 
> > > > > > > python main.py -c https://www.udemy.com/course/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/learn/lecture/ -q 720 --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > 
> > > 
> > > > > > > Could you kindly write what the new command would look like so I can copy and paste it into main.py?
> > > 
> > > 
> > > > > > > If I can't, I'll understand, but I would be immensely grateful if you could help.
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > no, I am not going to do it for you, you dont have to be in the programming field to read the readme file, theres literally a list of all the command arguments, along with examples already provided. It doesnt really seem like you've tried very hard.
> > > 
> > > 
> > > > > > theres a difference between helping and plain hand holding
> > > 
> > > 
> > > > > > https://github.com/Puyodead1/udemy-downloader#cookies
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > All good! But every way I try it doesn't work, believe me, yes, I read the Readme file, and even used the command **--browser chrome and --browser chrome --id-as-course-name**, I don't know where I put it is the cause of the error or if I have something else wrong with the script.
> > > 
> > > 
> > > > > This way it seems more logical to me: python main.py -c https://www.udemy.com/course/fundamentos-de-ethical-hacking/learn/lecture/ -q 720 **--browser chrome --id-as-course-name** --download-assets --download-captions --disable-ipv6 --log-level DEBUG
> > > 
> > > 
> > > > > I will continue trying here, anyway, thank you!
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Have you found a solution to the same problem?
> > > 
> > > 
> > > I still haven't been able to get it to work.
> > 
> > 
> > Well you're not going to get help when you don't even say what the problem is.
> 
> I'm leaving it to try again during this weekend, when I'll have more time, so I can tell you all the problems that occur here.

Is it working now?
