### ISSUE TITLE
[Bug]: unable to download assignment

### ISSUE THREAD

**Issue by jaephefd12** [Puyodead1/udemy-downloader#204]
### What happened?

Im unable to download assignments 
![IMG_6426](https://github.com/Puyodead1/udemy-downloader/assets/151659221/6ce8d268-e590-4275-a5a5-8c44e9b49074)

### Expected Result

5-10 folder of courses are blank because they are only assignments please can you help me with it sir?

### Branch

master/main

**Comment by Puyodead1** [comment]
> ### What happened?
> 
> Im unable to download assignments ![IMG_6426](https://private-user-images.githubusercontent.com/151659221/299676218-6ce8d268-e590-4275-a5a5-8c44e9b49074.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMjQ3ODYsIm5iZiI6MTcwNjIyNDQ4NiwicGF0aCI6Ii8xNTE2NTkyMjEvMjk5Njc2MjE4LTZjZThkMjY4LWU1OTAtNDI3NS1hNWE1LThjNDRlOWI0OTA3NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMjMxNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkyZDMzYjlmZGY4MzcyOGFhNTBjNjBlOWM2OWMxZmFhMDhiZTIyZmE4M2U4YmM5MThlOWVjM2RjZGVlZDZhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UYL1SuMQBQKMk8BEBXzfT_EtWqMRIovNQ_3f3e5FOxU)
> ### Expected Result
> 
> 5-10 folder of courses are blank because they are only assignments please can you help me with it sir?
> ### Branch
> 
> master/main

theres nothing to help with

**Comment by jaephefd12** [comment]
When downloading assets if there is any torrent it is getting stuck
![Uploading IMG_6444.png…]()
