### ISSUE TITLE
[Feature Request]: Bypass udemy download detection on drm encryted course.

### ISSUE THREAD

**Issue by Okenshield** [Puyodead1/udemy-downloader#205]
### Is your feature request related to a problem?

- [X] Yes
- [ ] No

### If yes, please describe

![image](https://github.com/Puyodead1/udemy-downloader/assets/100517297/d2c0e35e-646b-47e2-b4d0-f57e9daeab3d)

### Describe the solution you'd like

Bypass the detection

### Describe alternatives you've considered

would be nice if doesn't I downloaded the course

**Comment by Puyodead1** [comment]
no, stop trying to steal content from creators. this program was never meant to be used that way.
