### ISSUE TITLE
[Bug]: Shaka error when $ in file name

### ISSUE THREAD

**Issue by asdfmonster261** [Puyodead1/udemy-downloader#207]
### What happened?

shaka fails to decrypt the file when $ is in the file name with a file not found error

### Expected Result

to decrypt normally

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
No need for log, solution in other information.
```

### Other information

Add the following to line 1389 in main.py for everything to proceed as normal.

        .replace("$", "")

**Comment by Puyodead1** [comment]
This has already been fixed in feat/refactor
