### ISSUE TITLE
[Bug]: Checking after downloading

### ISSUE THREAD

**Issue by javadovrufiq99** [Puyodead1/udemy-downloader#210]
### What happened?

I wanted to check after downloading but, I got this error message:

![image](https://github.com/Puyodead1/udemy-downloader/assets/149192043/796fc7d6-65c6-46a6-8749-0be9875e7d4b)

### Expected Result

when I download a course, I can't get error. Checking after downloading I got this error message.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
please try the feat/refactor branch, the issue is caused by non-standard unicode characters

**Comment by chethanwiz** [comment]
> ### What happened?
> I wanted to check after downloading but, I got this error message:
> 
> ![image](https://private-user-images.githubusercontent.com/149192043/310058970-796fc7d6-65c6-46a6-8749-0be9875e7d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTYyMDUsIm5iZiI6MTcwOTc1NTkwNSwicGF0aCI6Ii8xNDkxOTIwNDMvMzEwMDU4OTcwLTc5NmZjN2Q2LTY1YzYtNDZhNi04NzQ5LTBiZTk4NzVlN2Q0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQyMDExNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDNmY2QxMzY4ZWM3ZDNjNzVkYTU4Y2YxM2QxZmQ1OGYzMmJlZGZiZjM5ZTc0NDdiZDkxOTI3YmJhYTk2ZmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uKzneF5DCEDfmUeCIUORM5fFEtmmn735HE9J0ddkri4)
> 
> ### Expected Result
> when I download a course, I can't get error. Checking after downloading I got this error message.
> 
> ### Branch
> master/main
> 
> ### What operating systems are you seeing the problem on?
> Windows
> 
> ### Relevant log output
> _No response_
> 
> ### Other information
> _No response_

how did you get the key id, i tried everything not able to get. can you let me know if possible
