### ISSUE TITLE
[Bug]: Unable to extract arguments from course page! Make sure you have a cookies.txt file!

### ISSUE THREAD

**Issue by coozgan** [Puyodead1/udemy-downloader#213]
### What happened?

What happened?
I am on personal plan, using macosx. I am able to download on my regular purchased course account. but not on this subscription type.
I can't proceed with download because it keeps on asking about "cookies.txt",
I have replicated what was use to resolve in [this ticket](https://github.com/Puyodead1/udemy-downloader/issues/185) but still no luck.

this are the things i have tried;
```
python3 main.py -c https://www.udemy.com/course/aws-certified-associate-architect-developer-sysops-admin/learn/lecture/15562114#overview --browser chrome
[pre_run:331] INFO: Output directory set to my/path/
[main:1934] INFO: > Fetching course information, this may take a minute...
[_extract_subscription_course_info:925] CRITICAL: Unable to extract arguments from course page! Make sure you have a cookies.txt file!
```

```
python3 main.py -c https://www.udemy.com/course/aws-certified-associate-architect-developer-sysops-admin/learn/lecture/15562114#overview --browser chrome --sc
[pre_run:331] INFO: Output directory set to my/path/
[main:1934] INFO: > Fetching course information, this may take a minute...
[_extract_subscription_course_info:925] CRITICAL: Unable to extract arguments from course page! Make sure you have a cookies.txt file!
```

this is my directory:
![Uploading Screenshot 2024-03-21 at 11.08.37 PM.png…]()

### Expected Result

able to download the course the same as my regular account

### Branch

master/main

### What operating systems are you seeing the problem on?

MacOS

### Relevant log output

```shell
'''
[pre_run:331] INFO: Output directory set to my/path/
[main:1934] INFO: > Fetching course information, this may take a minute...
[_extract_subscription_course_info:925] CRITICAL: Unable to extract arguments from course page! Make sure you have a cookies.txt file!
'''
```

**Comment by lesywix** [comment]
same issue

**Comment by coozgan** [comment]
Yeah, Sorry forgot to close this. I just didn't understand how it works. I realized I didn't need the cookies.txt for this method. Thanks!
