### ISSUE TITLE
[Bug]: Error extracting audio kid

### ISSUE THREAD

**Issue by H3LLMANBR** [Puyodead1/udemy-downloader#214]
### What happened?

Error extracting audio Kid, something that could be incorrectly configured?

### Expected Result

Solution

### Branch

master/main

**Comment by H3LLMANBR** [comment]
![image](https://github.com/Puyodead1/udemy-downloader/assets/161170381/074f7329-79c7-4d6d-bef1-bbf50164a547)

**Comment by Puyodead1** [comment]
Audio file missing, probably failed download or something
