### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory: when processing asset with special character on Windows

### ISSUE THREAD

**Issue by DavesNotHereDude** [Puyodead1/udemy-downloader#217]
### What happened?

**Error Provided:**

[01:35:18] [udemy-downloader] [parse_new:1787] INFO:     > Processing 1 asset(s) for lecture...
Traceback (most recent call last):
  File "C:\u\main.py", line 2067, in <module>
    main()
  File "C:\u\main.py", line 2060, in main
    parse_new(udemy, udemy_object)
  File "C:\u\main.py", line 1823, in parse_new
    file = open(file_path, "w")
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\u\\out_dir\\learn-digital-marketing-course\\07 - YouTube Marketing\\004 Whenever-you-provide-a-link-to-your-channel-add-sub-confirmation-1-to-the-end-of-your-channel-s-URL-and-a-pop-under-will-automatically-appear-on-your-channel-prompting-visitors-to-subscribe..url'

----------

**When attempting to process asset:**

![image](https://github.com/Puyodead1/udemy-downloader/assets/42450268/6cbe21f2-4969-4ccc-ac48-999de0df3d7d)

Element:

<span title="Whenever you provide a link to your channel, add “?sub_confirmation=1” to the end of your channel’s URL and a pop-under will automatically appear on your channel prompting visitors to subscribe." class="resource--ellipsis--5f0S7">Whenever you provide a link to your channel, add “?sub_confirmation=1” to the end of your channel’s URL and a pop-under will automatically appear on your channel prompting visitors to subscribe.</span>

### Expected Result

I believe the ? within the element is preventing a filename to be created (in Windows), causing the script to fail/end.

Expected Result could be to rewrite special character to supported character, or, report failure and bypass asset to move onto remaining assets. 

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
04/20 13:35:18 [NOTICE] Downloading 1 item(s)

04/20 13:35:18 [NOTICE] Download complete: C:/u/out_dir/learn-digital-marketing-course/07 - YouTube Marketing/004 How to Increase YouTube Subscribers by 400%_es.vtt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
93b819|OK  |   139KiB/s|C:/u/out_dir/learn-digital-marketing-course/07 - YouTube Marketing/004 How to Increase YouTube Subscribers by 400%_es.vtt

Status Legend:
(OK):download completed.
[01:35:18] [udemy-downloader] [process_caption:1564] DEBUG:       > Download return code: 0
[01:35:18] [udemy-downloader] [process_caption:1574] INFO:     > Converting caption to SRT format...
[01:35:18] [udemy-downloader] [process_caption:1576] INFO:     > Caption conversion complete.
[01:35:18] [udemy-downloader] [parse_new:1787] INFO:     > Processing 1 asset(s) for lecture...
Traceback (most recent call last):
  File "C:\u\main.py", line 2067, in <module>
    main()
  File "C:\u\main.py", line 2060, in main
    parse_new(udemy, udemy_object)
  File "C:\u\main.py", line 1823, in parse_new
    file = open(file_path, "w")
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\u\\out_dir\\learn-digital-marketing-course\\07 - YouTube Marketing\\004 Whenever-you-provide-a-link-to-your-channel-add-sub-confirmation-1-to-the-end-of-your-channel-s-URL-and-a-pop-under-will-automatically-appear-on-your-channel-prompting-visitors-to-subscribe..url'
```

### Other information

[Puyodead1](https://github.com/Puyodead1) For President

**Comment by Puyodead1** [comment]
path is too long, use --id-as-course-name

> [Puyodead1](https://github.com/Puyodead1) For President

haha

**Comment by DavesNotHereDude** [comment]
My bad, that works.

**Comment by techshad** [comment]
@DavesNotHereDude  hey, can you also help me out? 
error is :
Traceback (most recent call last):
  File "D:\Downloads\udemy-downloader-master\main.py", line 2051, in <module>
    main()
  File "D:\Downloads\udemy-downloader-master\main.py", line 2044, in main
    parse_new(udemy, udemy_object)
  File "D:\Downloads\udemy-downloader-master\main.py", line 1745, in parse_new
    file = open(file_path, "w")
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Downloads\udemy-downloader-master\out_dir\533682\14 - Mastering Java Lambdas Expressions, Interfaces, and Method References\234 Source-code-Lambda-Expressions-Functional-Interfaces-and-Method-References-Introduction-to-the-Lambda-Expression-and-Functional-Interfaces.url'

i read previous threads and used id as course name argument but still facing same error what do i need to do?
