### ISSUE TITLE
[Bug]: Error while trying to download from Udemy Business Plan Subscription

### ISSUE THREAD

**Issue by diaozheng1226** [Puyodead1/udemy-downloader#220]
### Hi, I have encountered a problem during usage, please help me, thank you very much.

firstly，I logged into my subscription account on Chrome for Windows.
![image](https://github.com/Puyodead1/udemy-downloader/assets/129975676/0980e2a2-f23e-4891-9e08-9f70b5919b4e)
"However, I encountered an error when executing the command."
![image](https://github.com/Puyodead1/udemy-downloader/assets/129975676/aec2039e-98a2-431c-8193-5b542ef38732)

### Expected Result

After reading the README file, I logged into my subscription account using Chrome, but the download still failed. I hope the cookies.txt file can be written to the current directory for easy access.

### Branch

master/main

**Comment by Puyodead1** [comment]
use feat/refactor and 
```
 -sc, --subscription-course
                        Mark the course as a subscription based course, use this if you are having problems with the program auto detecting it
```

**Comment by diaozheng1226** [comment]
hi,i use feat/refactor  , and I added the -sc parameter in the command, but it still throws an error
![image](https://github.com/Puyodead1/udemy-downloader/assets/129975676/beed18c4-82c6-4272-a3ba-2c8f2632f063)

**Comment by Puyodead1** [comment]
> @Puyodead1 hi,i use feat/refactor , and I added the -sc parameter in the command, but it still throws an error ![image](https://private-user-images.githubusercontent.com/129975676/329292495-beed18c4-82c6-4272-a3ba-2c8f2632f063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDg4MjIsIm5iZiI6MTcxNzUwODUyMiwicGF0aCI6Ii8xMjk5NzU2NzYvMzI5MjkyNDk1LWJlZWQxOGM0LTgyYzYtNDI3Mi1hM2JhLTJjOGYyNjMyZjA2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMzQyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjBkNmYyMjVkODMwMDhlZjBmMjExOGJlMmEwYmU2OTM3YzM1NGE4OWY1ZWFmMzBiMTIyMGZlZDBiMjNhZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lbesdcMjk-jROv6O9ZKNGs4IV7D-MVj1BIIG2IWunf8)

make sure you are logged in to ua.udemy.com in chrome, and that you close chrome before running the command
