### ISSUE TITLE
[Bug]: Downloading errors

### ISSUE THREAD

**Issue by javadovrufiq99** [Puyodead1/udemy-downloader#221]
### What happened?

I download a course without problem but, sometimes I got this error message:
![image](https://github.com/Puyodead1/udemy-downloader/assets/149192043/35448aec-e6ad-4a8e-affc-2c4812fe04c7)

### Expected Result

![image](https://github.com/Puyodead1/udemy-downloader/assets/149192043/fe3dc86b-5fd3-4c41-906c-b6ad3aeb7c57)

### Branch

master/main

**Comment by Puyodead1** [comment]
according to your report, the actual result is what your expected result is.

**Comment by javadovrufiq99** [comment]
@Puyodead1 This problem is unicode problem. Turkish characters doens't support. How to solve this?

I know Python basics only.

**Comment by Puyodead1** [comment]
> @Puyodead1 This problem is unicode problem. Turkish characters doens't support. How to solve this?
> 
> I know Python basics only. I didn't download some titles. For Example: 47, 48, 49 folder are empty. There is no videos in these folder. I tried to start to download again. Checked somes but others it wasn't downloaded.

I'm aware, the issue looks to be with logging specifically, I'm not really sure how to fix it, unicode has been a pain in the butt for a while now.

**Comment by javadovrufiq99** [comment]
> > @Puyodead1 This problem is unicode problem. Turkish characters doens't support. How to solve this?
> > I know Python basics only. I didn't download some titles. For Example: 47, 48, 49 folder are empty. There is no videos in these folder. I tried to start to download again. Checked somes but others it wasn't downloaded.
> 
> I'm aware, the issue looks to be with logging specifically, I'm not really sure how to fix it, unicode has been a pain in the butt for a while now.

![image](https://github.com/Puyodead1/udemy-downloader/assets/149192043/7671db36-59a3-4772-b244-850b0aa66f03)

These folders are empty. They were not downloaded.
