### ISSUE TITLE
ffmpeg merging files issue[Bug]: 

### ISSUE THREAD

**Issue by jaan143** [Puyodead1/udemy-downloader#224]
### What happened?

when ffmpeg merging audio and video files it is taking too much time to merge. before it wasn't take that long time.
it is showing some message like this
non-monotonous DTS in output stream 0:1; previous: 37256659, current 8144136; changing to 37987621. this may result in incorrect timestamps in the output file.

please see screenshot
![Screenshot 2024-06-09 181947](https://github.com/Puyodead1/udemy-downloader/assets/15013833/4dfa2c85-ed5a-451d-9191-e848c50bb611)

### Expected Result

script need to fix this issue and it should merge the files as it was doing before like months ago.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
Ffmpeg being slow for you isn't an issue with the script. Get a better PC or something.

**Comment by jaan143** [comment]
@Puyodead1 
i am not talking about slow. i am saying about this error before it was not showing but now it is showing so can you help to resolve this timestamp error ?

**Comment by Puyodead1** [comment]
> @Puyodead1 
> i am not talking about slow. i am saying about this error before it was not showing but now it is showing so can you help to resolve this timestamp error ?

It's not an error and you can ignore it

**Comment by jaan143** [comment]
@Puyodead1  first of all thanks for your update
now your latest updated script is not showing above ffmpeg errors but there is one problem that after dec files  script is not removing enc files and keeping them in folders too and just generating its dec file and tryting to dec again these files and then showing this message
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000131e0dce040] Found duplicated MOOV Atom. Skipped it
    Last message repeated 3 times
