### ISSUE TITLE
[Bug]:  403 Forbidden Error when trying to fetch details on Personal Pro Plan

### ISSUE THREAD

**Issue by nemokaul** [Puyodead1/udemy-downloader#225]
### What happened?

I am trying to fetch the info and check if everything works. I have done the setup as described in the README. And checked both the branch. Neither works and spits 403 Error. I am using  `-sc` and cookies as it is a Personal Pro Plan. The account is logged into the browser and I have also closed the browser when running the script. Also tried with brave and chrome. None works.

#### `master` branch
![image](https://github.com/Puyodead1/udemy-downloader/assets/107127291/04f279d9-edff-48c5-91a8-b483bdafaa7e)

#### `feat/refactor` branch
![image](https://github.com/Puyodead1/udemy-downloader/assets/107127291/4a6f527e-a631-4fd7-99a4-f3f640974589)

### Expected Result

The Info of the course should have been successfully displayed.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Other information

Microsoft Windows 11 [Version 10.0.22631.3296]

**Comment by Puyodead1** [comment]
You might be getting cloudflare captchas then

**Comment by nemokaul** [comment]
> You might be getting cloudflare captchas then

Is there a way to mitigate the issue or bypass the captchas ?

**Comment by Pherich** [comment]
I have the same issue recently,  is there a way to bypass the catches quickly?  thank you.

**Comment by Puyodead1** [comment]
no
