### ISSUE TITLE
Unlike mp4decrypter and aria2c, there is no check for ffmpeg.

### ISSUE THREAD

**Issue by legndery** [Puyodead1/udemy-downloader#23]
It throws the error when merging audio video but if there is an error it doesn't stop the execution it just ignores and starts downloading the next video

**Comment by Puyodead1** [comment]
This is so we can continue to download the segments, we don't always know if the error is specific to a lecture or not. I don't feel that quitting the program is thing.

**Comment by legndery** [comment]
hmm. but the `check_for_ffmpeg` thing already exists. and if ffmpeg doesn't exists it just throws the ffmpeg not found error and removes the segments as part of `cleanup`. Actually this happened to me I missed the readme and i downloaded for like 10-15mins but nothing showed in the out_dir, after that when i saw the logs i came to know that ffmpeg was not found.

**Comment by Puyodead1** [comment]
> 
> 
> hmm. but the `check_for_ffmpeg` thing already exists. and if ffmpeg doesn't exists it just throws the ffmpeg not found error and removes the segments as part of `cleanup`. Actually this happened to me I missed the readme and i downloaded for like 10-15mins but nothing showed in the out_dir, after that when i saw the logs i came to know that ffmpeg was not found.

Ah, I misunderstood what you were saying, my bad.
Yeah, that's a bug, I'll fix that in the next commit.
