### ISSUE TITLE
[Bug]: Fail To download some videos 

### ISSUE THREAD

**Issue by futuregate2016** [Puyodead1/udemy-downloader#230]
### What happened?

when downloading a course , some videos not download correctly , even srt file for videos not download in correct way , 
i think its because of Video title that contain some symbols , this screenshot show the videos issue : 
![Capture](https://github.com/user-attachments/assets/aee56ba8-e73b-4749-8ef7-0c56f33240ba)

### Expected Result

it will be great if can fix this issue and i can download this lecture

### Branch

master/main

**Comment by Puyodead1** [comment]
you expect me to tell you the issue when you didnt provide any useful information? a screenshot of the files doesnt tell me anything

**Comment by futuregate2016** [comment]
what info needed more sir ? 
can i sent u DM with my logins & Log ?

**Comment by Puyodead1** [comment]
> what info needed more sir ? can i sent u DM with my logins & Log ?

theres a bug report template for a reason, you didnt post any logs, errors, etc

**Comment by futuregate2016** [comment]
Look sir , i will attach downloader post and screenshot , 

[Downloader Post.txt](https://github.com/user-attachments/files/16186126/Downloader.Post.txt)


![Capture](https://github.com/user-attachments/assets/2499aee3-77fb-4671-9fd8-32eeee88d5dd)

**Comment by Puyodead1** [comment]
> Look sir , i will attach downloader post and screenshot ,
> 
> [Downloader Post.txt](https://github.com/user-attachments/files/16186126/Downloader.Post.txt)
> 
> ![Capture](https://private-user-images.githubusercontent.com/168378848/348060293-2499aee3-77fb-4671-9fd8-32eeee88d5dd.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDkzNDgsIm5iZiI6MTcyMDc0OTA0OCwicGF0aCI6Ii8xNjgzNzg4NDgvMzQ4MDYwMjkzLTI0OTlhZWUzLTc3ZmItNDY3MS05ZmQ4LTMyZWVlZTg4ZDVkZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMTUwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDQyYzhiNmI1YWYwMjhmNjM3Mzk4NGVhODg1YTEyYjJhZmE0ZTk1ZmMyYzY3OGJkOGY1Y2RmODUzODU2YzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VOg2UghkwDAivTFC6mFSboXlkNA-vXG8FeA32gLydg8)

Thank you for posting the errors you get when using the tool. #202 #142
