### ISSUE TITLE
[Bug]: Subtitles are not downloaded in the latest branch

### ISSUE THREAD

**Issue by Lollinoo** [Puyodead1/udemy-downloader#231]
### What happened?

I tried downloading the same course using the last two versions of the master branch (Before/After refactor branch) and noticed that subtitles are not downloaded in the last update.

### Expected Result

Command used: python .\main.py -c CourseURL -b cookie.txt --download-captions --skip-lectures --log-level DEBUG

### **BEFORE UPDATE:**

[12:23:24] [udemy-downloader] [parse_new:1786] INFO: Processing 15 caption(s)...
[12:23:24] [udemy-downloader] [process_caption:1566] INFO:     >  Downloading caption: '001 Introduction_en.vtt'

07/17 00:23:24 [NOTICE] Downloading 1 item(s)

07/17 00:23:24 [NOTICE] Download complete: C:/Users/User/Desktop/udemy-downloader-master-old/out_dir/ccna-complete/01 - Welcome/001 Introduction_en.vtt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e6815a|OK  |   426KiB/s|C:/Users/User/Desktop/udemy-downloader-master-old/out_dir/ccna-complete/01 - Welcome/001 Introduction_en.vtt

Status Legend:
(OK):download completed.
[12:23:24] [udemy-downloader] [process_caption:1569] DEBUG:       > Download return code: 0
[12:23:24] [udemy-downloader] [process_caption:1579] INFO:     > Converting caption to SRT format...
[12:23:24] [udemy-downloader] [process_caption:1581] INFO:     > Caption conversion complete.

-----------------------------------------------------------------------

### **AFTER UPDATE:**
[12:38:57] [udemy-downloader] [parse_new:1658] INFO: ======= Processing chapter 1 of 320=======
[12:39:00] [udemy-downloader] [parse_new:1710] INFO: Processing 0 caption(s)...
[12:39:04] [udemy-downloader] [parse_new:1710] INFO: Processing 0 caption(s)...
[12:39:04] [udemy-downloader] [parse_new:1710] INFO: Processing 0 caption(s)...
[12:39:05] [udemy-downloader] [parse_new:1710] INFO: Processing 0 caption(s)...
[12:39:08] [udemy-downloader] [parse_new:1710] INFO: Processing 0 caption(s)...

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
this is intentional, there was an issue where trying to get subtitles from the udemy API caused udemy to return http errors

**Comment by Lollinoo** [comment]
Ok, il problema riguarda solo i sottotitoli con seguente errore:
*upstream connect error or disconnect/reset before headers. reset reason: connection termination*

One workaround I am trying to work on is storing the “LectureIDs” and placing them within this new url:

LECTURE_URL = “https://{portal_name}.udemy.com/api-2.0/users/me/subscribed-courses/{course_id}/lectures/{lecture_id}/?fields[lecture]=asset,description,download_url&fields[asset]=asset_type,length,media_license_token,course_is_drmed,media_sources,captions,thumbnail_sprite,slides,slide_urls,download_urls,external_url”


Only from this url you can get the url of the subtitles

**Comment by Puyodead1** [comment]
> *upstream connect error or disconnect/reset before headers. reset reason: connection termination*
> 
> One workaround I am trying to work on is storing the “LectureIDs” and placing them within this new url:
> 
> ```python
> LECTURE_URL = “https://{portal_name}.udemy.com/api-2.0/users/me/subscribed-courses/{course_id}/lectures/{lecture_id}/?fields[lecture]=asset,description,download_url&fields[asset]=asset_type,length,media_license_token,course_is_drmed,media_sources,captions,thumbnail_sprite,slides,slide_urls,download_urls,external_url”
> ```
> 
> 
> Only from this api you can get the url of the subtitles, but this will greatly complicate the flow of the program

That's just not feasible

**Comment by Muhammed-Osamaa** [comment]
i have the same issue

**Comment by Puyodead1** [comment]
This issue may be fixed in 2d6a3020aab0612630fd650587c05b5d89b0892c, they seem to be downloading fine for me in a course with 182 lectures.
