### ISSUE TITLE
[Bug]: Exception: [download_helper.cc:562] errorCode=1 Failed to open the file

### ISSUE THREAD

**Issue by dark-ryuk** [Puyodead1/udemy-downloader#232]
### What happened?

I don't know much about the error but by looking at the logs the error seems to be in aria2c, The downloaded fragment can't 
delegate the fragments to aria2c, for the DRM content

![Screenshot 2024-07-23 204447](https://github.com/user-attachments/assets/69c9bd27-8fdd-4645-8e54-543d46ffe268)
![Screenshot 2024-07-23 210224](https://github.com/user-attachments/assets/c36a7aeb-4a63-4f4e-9375-c6497d97f436)

### Expected Result

The expected result is that the content should get downloaded in .mp4 successfully

### Branch

master/main

**Comment by Puyodead1** [comment]
This is a common thing people are opening issues about, you can find many that have already been answered by searching existing issues.

Path is too long, move closer to root of drive and/or use --id-as-course-name
