### ISSUE TITLE
[Bug]: codec erorr

### ISSUE THREAD

**Issue by jaephefd12** [Puyodead1/udemy-downloader#234]
### What happened?

![IMG_0178](https://github.com/user-attachments/assets/f0f0e227-a316-4ace-bbe0-84d861bc5493)

### Expected Result

![IMG_0177](https://github.com/user-attachments/assets/21b01952-0187-4c09-b81c-e14b8f43f41e)

### Branch

master/main

### Relevant log output

```shell
Everything is installed added key ffmepg ffprobe shaka aria2c but still this erorr

Video files are only 1kb
```

**Comment by Puyodead1** [comment]
Try an older version: https://github.com/Puyodead1/udemy-downloader/commit/4b80e32433dd341a2eaccdd60aa60cb6588b7900

**Comment by jaephefd12** [comment]
Thanks for reply, issue was ffmepg version or something i added diff versions of ffmepg ffprobe maybe

**Comment by Puyodead1** [comment]
> Thanks for reply, issue was ffmepg version or something i added diff versions of ffmepg ffprobe maybe

Interesting, glad you figured it out 👍🏻

**Comment by jaephefd12** [comment]
![Uploading IMG_0182.png…]()

**Comment by erahaman** [comment]
> Thanks for reply, issue was ffmepg version or something i added diff versions of ffmepg ffprobe maybe

How did you manage to solve the problem, I facing it right now, you download a new version or what of ffmpef?
