### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) error when downloading courses

### ISSUE THREAD

**Issue by denes44** [Puyodead1/udemy-downloader#239]
### What happened?

Doesn't matter which parameters I use, I always got the error message below.

### Expected Result

I expected the download of a source successful.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
D:\udemy-downloader-master>main.py -c "https://www.udemy.com/course/[course_name]/learn/" --browser chrome --log-level DEBUG
Traceback (most recent call last):
  File "D:\udemy-downloader-master\main.py", line 1179, in <module>
    audio_key: Union[str | None] = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Puyodead1** [comment]
You need python 3.10 or higher
