### ISSUE TITLE
Windows: "the command line is too long" in "copy /b" command for large lectures (more than 1hr 20mins)

### ISSUE THREAD

**Issue by legndery** [Puyodead1/udemy-downloader#24]
details: https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation

The workaround for now I am using is dividing the copy /b into multiple batches. 
like,
`touch encrypted_video.mp4  encrypted_audio.mp4`
then, `copy /b encrypted_video.mp4+video_0......+video_249.mp4`
..next batch..
`copy /b encrypted_video.mp4+video_250......+video_499.mp4` .. and so on.

So the number of segment i have is ~1045.

**Comment by Puyodead1** [comment]
this issue is resolved in the ``feat-ytdlp branch``
