### ISSUE TITLE
does not see any personal plan lessons that have not been purchased

### ISSUE THREAD

**Issue by forfreal2** [Puyodead1/udemy-downloader#248]
### What happened?

I signed up for a 1 week free trial personal plan membership and added one free and one personal plan course to the account

free course udemy.com/course/excel-dizi-formulleri/
personel plan course udemy.com/course/excelegitim/

downloaded the free course without any problems but gave an error while downloading the personal plan course

error

Failed request https://www.udemy.com/course/excelegitim/learn
[03:24:07] [udemy-downloader] [_get:1114] ERROR: 403 Forbidden, retrying (attempt 0 )...

When I query it via the API link below, it sees the free course but not the course for the personal plan.

[https://www.[udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=excel-dizi-formulleri]](https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=excel-dizi-formulleri)

![22](https://github.com/user-attachments/assets/803f01ba-6492-478b-bda5-61a4d0b7652a)

https://www.[udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=excelegitim](https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=excelegitim)

![11](https://github.com/user-attachments/assets/56947443-8077-4986-bff9-fb5c397b3a1f)

Can you help me about this issue?

### Expected Result

downloaded

### Branch

Other (Enter below)

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
because subscription courses are not owned by you... thats why the -sc option exists, use with --browser

**Comment by forfreal2** [comment]
> because subscription courses are not owned by you... thats why the -sc option exists, use with --browser

py main.py -c https://www.udemy.com/course/excelegitim/learn --browser brave -sc

like this but still 

Fetching course information, this may take a minute...
[03:35:01] [udemy-downloader] [_get:1113] ERROR: Failed request https://www.udemy.com/course/excelegitim/learn
[03:35:01] [udemy-downloader] [_get:1114] ERROR: 403 Forbidden, retrying (attempt 0 )...

**Comment by Puyodead1** [comment]
> > because subscription courses are not owned by you... thats why the -sc option exists, use with --browser
> 
> py main.py -c https://www.udemy.com/course/excelegitim/learn --browser brave -sc
> 
> like this but still
> 
> Fetching course information, this may take a minute... [03:35:01] [udemy-downloader] [_get:1113] ERROR: Failed request https://www.udemy.com/course/excelegitim/learn [03:35:01] [udemy-downloader] [_get:1114] ERROR: 403 Forbidden, retrying (attempt 0 )...

are you logged in to udemy in brave? most likely you are being served a cloudflare challenge

**Comment by forfreal2** [comment]
> > > because subscription courses are not owned by you... thats why the -sc option exists, use with --browser
> > 
> > 
> > py main.py -c https://www.udemy.com/course/excelegitim/learn --browser brave -sc
> > like this but still
> > Fetching course information, this may take a minute... [03:35:01] [udemy-downloader] [_get:1113] ERROR: Failed request https://www.udemy.com/course/excelegitim/learn [03:35:01] [udemy-downloader] [_get:1114] ERROR: 403 Forbidden, retrying (attempt 0 )...
> 
> are you logged in to udemy in brave? most likely you are being served a cloudflare challenge

Yes, I logged in, it downloads the purchased courses, but if it's because of cloudflare, shouldn't it download them too?
