### ISSUE TITLE
Assets download problem when 2 assets have the same name in a same chapter

### ISSUE THREAD

**Issue by mthibaut-hbc** [Puyodead1/udemy-downloader#25]
It could be a good idea to add `object_index ` to assets because when You try to download a course with 2 assets with the same name in the same chapter, You got a error ....

I06/01 13:16:16 [ERROR] CUID#7 - Download aborted. URI=https://att-c.udemycdn.com/2021-04-20_07-32-14-b1cd60e7a5afc2dac7fbab5003bcb8a1/original.zip?response-content-disposition=attachment%3B+filename%3DCourseDBFunction.zip&Expires=1622556964&Signature=XXXXXXXX
Exception: [AbstractCommand.cc:403] errorCode=13 URI=https://att-c.udemycdn.com/2021-04-20_07-32-14-b1cd60e7a5afc2dac7fbab5003bcb8a1/original.zip?response-content-disposition=attachment%3B+filename%3DCourseDBFunction.zip&Expires=1622556964&Signature=XXXXXXXX
  -> [RequestGroup.cc:784] errorCode=13 File c:/udemy-downloader/out_dir/exam-microsoft-azure-dev/04 Develop Azure compute solutions - Azure Web Apps and Azure Functions/CourseDBFunction.zip exists, but a control file(*.aria2) does not exist. Download was canceled in order to prevent your file from being truncated to 0. If you are sure to download the file all over again, then delete it or add --allow-overwrite=true option and restart aria2.

06/01 13:20:48 [ERROR] CUID#7 - Download aborted. URI=https://att-c.udemycdn.com/2021-04-20_07-35-15-82a6966be87c277bcdb41df01a145775/original.zip?response-content-disposition=attachment%3B+filename%3DCourseDBFunction.zip&Expires=1622556964&Signature=XXXXXXXX
Exception: [AbstractCommand.cc:403] errorCode=13 URI=https://att-c.udemycdn.com/2021-04-20_07-35-15-82a6966be87c277bcdb41df01a145775/original.zip?response-content-disposition=attachment%3B+filename%3DCourseDBFunction.zip&Expires=1622556964&Signature=XXXXXXXX
  -> [RequestGroup.cc:784] errorCode=13 File c:/udemy-downloader/out_dir/exam-microsoft-azure-dev/04 Develop Azure compute solutions - Azure Web Apps and Azure Functions/CourseDBFunction.zip exists, but a control file(*.aria2) does not exist. Download was canceled in order to prevent your file from being truncated to 0. If you are sure to download the file all over again, then delete it or add --allow-overwrite=true option and restart aria2.

**Comment by Puyodead1** [comment]
This should be resolved now. Thank you for the report!
