### ISSUE TITLE
[Bug]: Error obtaining cookies with -sc and --browser brave on Windows 10

### ISSUE THREAD

**Issue by Zheone9** [Puyodead1/udemy-downloader#255]
### What happened?

 I have been trying to download a course using my Udemy personal subscription. I used the commands `-sc` and `--browser brave` to get the cookies from my Brave browser, but when attempting to retrieve the cookies, I encounter a privilege error. It doesn't work even when I open a terminal with administrator rights.

![image](https://github.com/user-attachments/assets/5a6b3636-b5e8-4903-b3a1-23e27eb455a1)

### Expected Result

Cookies should be successfully retrieved without any errors.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Jorge\\AppData\\Roaming\\..\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Network\\Cookies'
```

**Comment by Puyodead1** [comment]
close brave lol

**Comment by Puyodead1** [comment]
> > close brave lol
> 
> I solved this error with the `--browser file` and putting my cookies into the file cookies.txt

I mean... all you need to do is close brave... but sure
