### ISSUE TITLE
File not found error when download start

### ISSUE THREAD

**Issue by neil89** [Puyodead1/udemy-downloader#34]
Hi,

first of all, thanks for creating this tool. I'm sure this can make the trick to download my purchased courses in Udemy. Though this, I'm getting to different errors:

I added required libraries to the path:

![image](https://user-images.githubusercontent.com/1921323/125781238-8409adb6-9693-423a-a430-0847922182c8.png)

and also edit my `.env` file (though finally I write Bearer token in command line). File keyfile.json is renamed but I kept as is, since I think I don't neet it because I actually have purchased access to this courses.

1. Running `python main.py -c https://...#overview -b xxx`

After all lectures are processed, I get this error:

![image](https://user-images.githubusercontent.com/1921323/125781270-205ff645-4e0b-4855-848e-3440a915f677.png)

Which is something like "FileNotFoundError: [WinError 2] System cannot find the specified file". Only a couple of html files were downloaded.

2. Running `python main.py -c https://...#overview -b xxx --skip-hls`

After all lectures are processed, I actually download several videos, but...:

![image](https://user-images.githubusercontent.com/1921323/125781138-56bb54d2-899c-44b4-bde1-367053807828.png)
![image](https://user-images.githubusercontent.com/1921323/125781480-6d4895af-670b-4d8e-b46c-01fa767e793f.png)

I've got no idea what is failing and how to solve.

**Comment by Puyodead1** [comment]
> File keyfile.json is renamed but I kept as is, since I think I don't neet it because I actually have purchased access to this courses.
the keyfile has nothing to do with wither or not you purchased the courses, its for courses that have lectures with DRM on them, which your course has.

The rest of the errors are because you're missing ``yt-dlp``, looks like I forgot to add that to the requirements list.
``pip install yt-dlp`` should install it

**Comment by neil89** [comment]
Thanks for your answer @Puyodead1 ! 

Ok, I tried to install `yt-dlp`, but looks like it already was there:

![image](https://user-images.githubusercontent.com/1921323/125907162-18f9f712-1525-4d4c-b7b8-ea288a01ef69.png)

After that, I tried to download again using `--skip-hls` option, but...

![image](https://user-images.githubusercontent.com/1921323/125907358-ce55ab8a-d3b5-4ccd-b1eb-2a8cd8a9a1cc.png)

I think this is because keyfile is empty... There is any way to download my legally purchase course and not incurring in piracy? I have never user a decrypter or something like this... 

Thanks in advance

**Comment by Puyodead1** [comment]
> Ok, I tried to install yt-dlp, but looks like it already was there:

My guess is that your python scripts folder isn't in your path, are you able to run ``yt-dlp`` in powershell on its own?

> I think this is because keyfile is empty...

The error is not related to the keyfile, you can follow the stack trace to the exact line that causes the error which is related to yt-dlp. 

> There is any way to download my legally purchase course and not incurring in piracy? I have never user a decrypter or something like this...

Not really, this tool requires you to provide decryption keys for the encrypted content and to my knowledge there are no longer any public methods to acquire these as of May 31, 2021. This means that you can download all the lectures, but the ones that have DRM encryption will be unplayable.

**Comment by Puyodead1** [comment]
Closing this due to no response.
