### ISSUE TITLE
index error: list index out of range

### ISSUE THREAD

**Issue by maamirsaeed** [Puyodead1/udemy-downloader#4]
am getting an error after following all the steps. I have retrieved all the information but i guess there is something wrong with the code. 
Error
Fetching Course data, this may take a minute...
Course data retrieved!
Traceback (most recent call last):
  File "main.py", line 288, in <module>
    parse(data["results"])
  File "main.py", line 242, in parse
    chapters[-1]["lectures"].append(obj)
IndexError: list index out of range
![error](https://user-images.githubusercontent.com/84435386/118764081-941aac00-b881-11eb-8dc9-2c329af6c6bb.png)

**Comment by Puyodead1** [comment]
Would you be willing to email me your course id and bearer token so i can take a look? ``puyodead@protonmail.com``

**Comment by maamirsaeed** [comment]
> Would you be willing to email me your course id and bearer token so i can take a look? `puyodead@protonmail.com`

I've send you the course id and the bearer token to your mail
