### ISSUE TITLE
Encrypted files downloaded but not merged

### ISSUE THREAD

**Issue by mohgabr** [Puyodead1/udemy-downloader#45]
Encrypted files are downloaded normally but two files per video one with `mp4` and one with `m4a` extensions and they are not merged
Does anyone have an idea how to merge the whole directory?

**Comment by mohgabr** [comment]
It was error in the key, when I fixed the key it worked
Thanks for the great work

**Comment by ekorudiawan** [comment]
Hi, how do you fix the key, some problem with me

**Comment by Puyodead1** [comment]
> 
> 
> Hi, how do you fix the key, some problem with me

use the right decryption key
