### ISSUE TITLE
Error: Please accept our latest Terms of Service.

### ISSUE THREAD

**Issue by pandapaddel** [Puyodead1/udemy-downloader#5]
Im getting this error while fetching the course data:
Fetching Course data, this may take a minute...
An error occurred while trying to fetch the course data! {"error": "Please accept our latest Terms of Service."}

**Comment by Puyodead1** [comment]
Thats interesting, are you able to watch lectures on udemy.com?

**Comment by pandapaddel** [comment]
yes, I can watch lectures on udemy.
Problem is solved - Im using udemy business and I had to adjust the url (from udemy.com to company.udemy.com)
