### ISSUE TITLE
ModuleNotFoundError: No module named 'sanitize_filename' 'dotenv'

### ISSUE THREAD

**Issue by MiaBluette** [Puyodead1/udemy-downloader#51]
I'm on Macbook BigSur 11.5.2. The Udeler latest version doesn't work for me :"<
Screentshot: https://prnt.sc/1raqo9f]
Hope someone can lend me some help.

PS: thank you for developing this tool.

**Comment by Puyodead1** [comment]
This isn't udler and you need to install the requirements.
``pip install -r requirements.txt``
