### ISSUE TITLE
I have no idea how to use this

### ISSUE THREAD

**Issue by fasilmrm** [Puyodead1/udemy-downloader#52]
i need to download a course and i need it very badly. But i have no idea how to use this method.

**Comment by Puyodead1** [comment]
Read the README file

**Comment by fasilmrm** [comment]
I did bro. I did'nt understand anything. 😐

**Comment by CHITTIMOTU** [comment]
We need bellow 2 requirements  to use this program. earlier we  used a chrome extension to get those. But that method not working after extension revoked and blocked by Google and Widevine at May 31st.

Decryption Key ID
Decryption Key

But currently  there currently no public way to get those keys. I don't know how other users are getting those keys and using this program, if someone helps ( may be not in this repo, other external link or personal message please)

even if any paid tool available to get those keys, please let us know.

**Comment by Puyodead1** [comment]
> We need bellow 2 requirements  to use this program. earlier we  used a chrome extension to get those. But that method not working after extension revoked and blocked by Google and Widevine at May 31st.
> 
> 
> 
> Decryption Key ID
> 
> Decryption Key
> 
> 
> 
> But currently  there currently no public way to get those keys. I don't know how other users are getting those keys and using this repo, if someone helps ( may be not in this repo, other external link or personal message please)
> 
> 
> 
> even if any paid tool available to get those keys, please let us know.
> 
> 
> 
> 

There is a public way to get keys

**Comment by gyurix** [comment]
Well @CHITTIMOTU that's kinda good, because it prevents them patching the way to obtain those decryption keys :)

Your best bet would be to join the Discord server and ask for help about these privately from people claiming to be able to use this software or just look around on the internet until you find the solution.

**Comment by CHITTIMOTU** [comment]
> Read the README file

@Puyodead1 , you may be not happy if i talk about Decryption key and id, but please can you refer/help any other way to get those, at list is there any free  working solution available ? 
i spent more than a week to find the solution in the internet, but unfortunately i didn't fine any,
i saw few others claiming that they have dark tools to get these keys but they are asking big amount of money,  also  they  seems to be a scam,  not sure how much genuine they are

**Comment by Puyodead1** [comment]
> > Read the README file
> 
> 
> 
> @Puyodead1 , you may be not happy if i talk about Decryption key and id, but please can you refer/help any other way to get those, at list is there any free  working solution available ? 
> 
> i spent more than a week to find the solution in the internet, but unfortunately i didn't fine any,
> 
> i saw few others claiming that they have dark tools to get these keys but they are asking big amount of money,  also  they  seems to be a scam,  not sure how much genuine they are 
> 
>  

There's been a free tool on GitHub for a few weeks now. Widevine-l3-guesser
