### ISSUE TITLE
[Feature Request] HEVC H.265

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#55]
First i would thank you @Puyodead1 for his efforts and time for developing tis repo
with this tool, I am sharing few coerces on cloud drive (like one drive)  for my students, and they can able to download and access from internet

But this tool creating video's in AVC -H.264  format , so it consumes much disk space and internet bandwidth for upload and downlead. and ffmpg [supports](https://trac.ffmpeg.org/wiki/Encode/H.265) HEVC H265 format, so, i request to give on option to create the video's in H265 format

For more details about HEVC can be found [here](https://www.macxdvd.com/mac-dvd-video-converter-how-to/h265-vs-h264.htm)

i am using [MediaInfo](https://mediaarea.net/en/MediaInfo/Download) tool for identifying the codec. and HEVC is the best codec for high quality video's with less disk space
 also request to integrate sub titles inside .MP4 container, so it will reduce the number of files in disks, and helpful for my student's to handle, 

Thank you!

**Comment by Puyodead1** [comment]
Sure, I'll work on this tomorrow (currently 11pm for me)

**Comment by Ex-Communicad0** [comment]
hi @Puyodead1 also please add a logging system like udemy-dl.log if you can

**Comment by CHITTIMOTU** [comment]
Hi @Puyodead1 

I am getting module error , Can you please confirm, am i missing anything here? 


D:\UDL\udemy_downloader>UdemyDownloader.py -c https://tcsglobal.udemy.com/course/introduction-to-cloud-computing/learn/lecture/4430906?start=0#overview --download-assets --download-captions --use-h265
Traceback (most recent call last):
  File "D:\UDL\udemy_downloader\UdemyDownloader.py", line 38, in <module>
    from udemy_downloader.sanitize import sanitize, slugify, SLUG_OK
ModuleNotFoundError: No module named 'udemy_downloader'

D:\UDL\udemy_downloader>

**Comment by Puyodead1** [comment]
> 
> 
> Hi @Puyodead1
> 
> I am getting module error , Can you please confirm, am i missing anything here?
> 
> D:\UDL\udemy_downloader>UdemyDownloader.py -c https://tcsglobal.udemy.com/course/introduction-to-cloud-computing/learn/lecture/4430906?start=0#overview --download-assets --download-captions --use-h265
> Traceback (most recent call last):
> File "D:\UDL\udemy_downloader\UdemyDownloader.py", line 38, in
> from udemy_downloader.sanitize import sanitize, slugify, SLUG_OK
> ModuleNotFoundError: No module named 'udemy_downloader'
> 
> D:\UDL\udemy_downloader>

That's a problem from my end, just pushed a fix. Give it a try

**Comment by CHITTIMOTU** [comment]
Now getting this error

Traceback (most recent call last):
  File "D:\UDL2\udemy_downloader\UdemyDownloader.py", line 38, in <module>
    from sanitize import sanitize, slugify, SLUG_OK
  File "D:\UDL2\udemy_downloader\sanitize.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'

D:\UDL2\udemy_downloader>

**Comment by Puyodead1** [comment]
> 
> 
> Now getting this error
> 
> Traceback (most recent call last):
> File "D:\UDL2\udemy_downloader\UdemyDownloader.py", line 38, in
> from sanitize import sanitize, slugify, SLUG_OK
> File "D:\UDL2\udemy_downloader\sanitize.py", line 19, in
> import six
> ModuleNotFoundError: No module named 'six'
> 
> D:\UDL2\udemy_downloader>

huh, I guess I accidentally removed that dependency
install it with ``pip install six``

**Comment by CHITTIMOTU** [comment]
installing SIX worked!!, Thanks
And got another error

!!! Keyfile not found! This means you probably didn't rename the keyfile correctly, DRM lecture decryption will fail! If you aren't downloading DRM encrypted courses, you can ignore this message. !!!
Waiting for 10 seconds...
Traceback (most recent call last):
  File "D:\UDL2\udemy_downloader\UdemyDownloader.py", line 1024, in <module>
    UdemyDownloader()
  File "D:\UDL2\udemy_downloader\UdemyDownloader.py", line 950, in UdemyDownloader
    load_keys()
  File "D:\UDL2\udemy_downloader\UdemyDownloader.py", line 937, in load_keys
    f = open(keyfile_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\UDL2\\udemy_downloader\\keyfile.json'

But managed this by copying keyfile inside udemy_downloader  sub folder!!

**Comment by Puyodead1** [comment]
> installing SIX worked!!, Thanks

great!

> But managed this by copying keyfile inside udemy_downloader sub folder!!

ah, that's a bug. I'll fix that in the next commit. Thank you

**Comment by CHITTIMOTU** [comment]
one more observation, 
i used "--download-captions" option, but still subtitles not downloaded,

can you please look into it,
Also is there any way to merge the subtitles, inside .mp4 container, i can do this with  mkvmerge but it creates  .mkv,
but i prefer i need it in .mp4, so my students can stream .mp4 from gdrive or cloud drive without downloading them

**Comment by CHITTIMOTU** [comment]
Hi @Puyodead1 
another one observation,

only DRM protected videos are creating as HEVC H265 format
non DRM videos ( first few videos like introduction) are still in AVC format, 
i believe these are not passed through ffmpeg, but is there any fix  that please

**Comment by CHITTIMOTU** [comment]
Hi @Puyodead1 
want to tell you a big thanks to you for considering my request
just wan to share the comparison , i expected at list 40% to  50% size reduction
but now i got more than that without loosing quality

80MB becomes 14MB now!!, 

![image](https://user-images.githubusercontent.com/65209890/134760985-5c96272a-91a9-487b-b7b4-9bdbcb11e551.png)

**Comment by Puyodead1** [comment]
> 
> 
> one more observation,
> i used `--download-captions` and `--download-assets` option, but still subtitles and assets are not downloaded,
> 
> can you please look into it,
> Also is there any way to merge the subtitles, inside .mp4 container, i can do this with mkvmerge but it creates .mkv,
> but i prefer i need it in .mp4, so my students can stream .mp4 from gdrive or cloud drive without downloading them

I've fixed the captions, I couldn't reproduce the issue with assets though. I believe it is possible to use ffmpeg to merge subtitles into an mp4, see [here](https://stackoverflow.com/a/17584272)




> 
> 
> Hi @Puyodead1
> another one observation,
> 
> only DRM protected videos are creating as HEVC H265 format
> non DRM videos ( first few videos like introduction) are still in AVC format,
> i believe these are not passed through ffmpeg, but is there any way to convert then into HEVC

I've fixed this locally but I'm still trying to get it to work correctly so I havn't pushed it yet.

**Comment by CHITTIMOTU** [comment]
> I believe it is possible to use ffmpeg to merge subtitles into an mp4, see [here](https://stackoverflow.com/a/17584272)
it's great to hear, but i am completely dumb in coding,  can i ask you to implement this in your next push


> I've fixed this locally but I'm still trying to get it to work correctly so I havn't pushed it yet.
Eagerly waiting for your next push, then i have a lot to re-download all my courses with HEVC. Once again a big thanks to you

**Comment by Puyodead1** [comment]
I just pushed a new commit for non-drm videos not encoding to h265. I think i got it working correctly now.


> it's great to hear, but i am completely dumb in coding, can i ask you to implement this in your next push

Yeah, I can look into adding this for the next commit

**Comment by CHITTIMOTU** [comment]
> I just pushed a new commit for non-drm videos not encoding to h265. I think i got it working correctly now.

Great news for me, But i am getting this error again, please help me!

![image](https://user-images.githubusercontent.com/65209890/134784321-05389b75-8e84-4d40-8957-7dfd38f05576.png)

**Comment by Puyodead1** [comment]
> 
> 
> > I just pushed a new commit for non-drm videos not encoding to h265. I think i got it working correctly now.
> 
> Great news for me, But i am getting this error again, please help me!
> 
> ![image](https://user-images.githubusercontent.com/65209890/134784321-05389b75-8e84-4d40-8957-7dfd38f05576.png)

You should be running it with `python udemy_downloader [options]`

**Comment by CHITTIMOTU** [comment]
> You should be running it with `python udemy_downloader [options]`, check the examples here:

i tried that before , but got different error, and i checked my access token, it's correct

![image](https://user-images.githubusercontent.com/65209890/134784754-3aea350e-f896-420c-aaf8-d47473f84ee4.png)

**Comment by Puyodead1** [comment]
> 
> 
> > You should be running it with `python udemy_downloader [options]`, check the examples here:
> 
> i tried that before , but got different error, and i checked my access token, it's correct
> 
> ![image](https://user-images.githubusercontent.com/65209890/134784754-3aea350e-f896-420c-aaf8-d47473f84ee4.png)
Looks like a bug related to using the .env file, can you try passing it through the command with the -b option?

**Comment by Puyodead1** [comment]
I've pushed a fix for the above issue actually

**Comment by CHITTIMOTU** [comment]
Sure, But a small request
can you delete all the cmd images which i pasted above, i don't want to expose the business udemy account in the link, which i am using
it's a security issue for me

**Comment by Puyodead1** [comment]
> 
> 
> Sure, But a small request
> can you delete all the cmd images which i pasted above, i don't want to expose the business udemy account in the link, which i am using
> it's a security issue for me

sure

**Comment by CHITTIMOTU** [comment]
Everything seems working now. but want to ask another one, please ignore, if this is too much

while encoding HEVC video, CPU usage is 100%, may be we are using soft encoding, and my graphic card is not working for this process
![image](https://user-images.githubusercontent.com/65209890/134785241-5785c929-7a4f-4ce9-acb5-5198b0031c8a.png)

I checked that FFmpeg supports [Hardware Acceleration](https://trac.ffmpeg.org/wiki/HWAccelIntro), is it possible to add [libmfx](https://trac.ffmpeg.org/wiki/Hardware/QuickSync) support for faster video encoding
libmfx id for windows machines for intel processors

**Comment by Puyodead1** [comment]
> 
> 
> Everything seems working now. but want to ask another one, please ignore, if this is too much
> 
> while encoding HEVC video, CPU usage is 100%, may be we are using soft encoding, and my graphic card is not working for this process
> ![image](https://user-images.githubusercontent.com/65209890/134785241-5785c929-7a4f-4ce9-acb5-5198b0031c8a.png)
> 
> I checked that FFmpeg supports [Hardware Acceleration](https://trac.ffmpeg.org/wiki/HWAccelIntro), is it possible to add [libmfx](https://trac.ffmpeg.org/wiki/Hardware/QuickSync) support for faster video encoding
> libmfx id for windows machines for intel processors

as far as i know, you have to build ffmpeg with libmfx support

**Comment by CHITTIMOTU** [comment]
> as far as i know, you have to build ffmpeg with libmfx support

Let me find a way from google to build this ,meanwhile  if you know any links/ reference, please share , it will help me a lot

**Comment by CHITTIMOTU** [comment]
Finally got it, After changing codec i got 4.5x speed encoding with GPU Processing

![image](https://user-images.githubusercontent.com/65209890/134787025-9acaa943-5a2f-451f-9936-08897f7b0aa8.png)

![image](https://user-images.githubusercontent.com/65209890/134787059-9cca7439-33ac-454b-b797-b51512607583.png)

ffmpeg comes with `hevc_qsv  `           HEVC (Intel Quick Sync Video acceleration) (codec hevc)  encoder by default

![image](https://user-images.githubusercontent.com/65209890/134787123-d4c1c285-c51f-45f3-bdac-cb17ffe8720c.png)

so i replaced it from bellow 3 files

![image](https://user-images.githubusercontent.com/65209890/134787116-ed25edd9-2bb4-44cf-9fac-41ac1afcd439.png)

Is it possible to input encoder type as a command line option after `--use-h265 ` so we can choose it based on CPU/ Graphic card

**Comment by Puyodead1** [comment]
Yeah! I’ll add that in a little bit. Glad you got it working

**Comment by Puyodead1** [comment]
I'm going to go ahead and close this now since it's been added
