### ISSUE TITLE
[BUG] pdf assets are creating with random file names at beginning 

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#56]
**Describe the bug**
pdf assets are creating with random file names at beginning 

**Expected behavior**
Master branch  versions able  to download pdf with correct file names

**Screenshots**
![image](https://user-images.githubusercontent.com/65209890/134815534-ffa8cddf-7444-4a06-a44b-96b417b4449d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - You are running version 1.2.2 (development branch)

**Comment by Puyodead1** [comment]
This is the same as the master branch, it appends the asset id to the start. I pushed a new commit to the develop branch that removes it.

**Comment by CHITTIMOTU** [comment]
@Puyodead1 

i tried with resent "develop" branch with `--skip-lectures --download-assets` options
but empty folders created without any pdf files

i tried multiple times with different coerces, but still same problem

**Comment by Puyodead1** [comment]
Are you still having this issue?

**Comment by Puyodead1** [comment]
Closing due to no response
