### ISSUE TITLE
Getting aria2c error code

### ISSUE THREAD

**Issue by Aakash132** [Puyodead1/udemy-downloader#58]
I am getting this error. Please help me solve this error
![Screenshot (5)](https://user-images.githubusercontent.com/69832804/135319440-28999b30-bfa9-40a8-b57c-b4ff93e9e8d5.png)
![Screenshot (4)](https://user-images.githubusercontent.com/69832804/135319445-640c7057-4663-424f-9c52-0086a44e10ac.png)
.

**Comment by Puyodead1** [comment]
If you are still getting these errors, please try the latest version of udemy-downloader and aria2c
