### ISSUE TITLE
[BUG] "Course ID not found" error on Courses that were obtained Through the Personal Plan

### ISSUE THREAD

**Issue by pryach** [Puyodead1/udemy-downloader#59]
**Describe the bug**
Downloading of courses that were obtained through subscriptions such as the **Personal Plan Free Trial** do not work.  I am able to download courses that I purchased but not Personal Plan courses.

**To Reproduce**
1. Get the [Personal Plan](https://support.udemy.com/hc/en-us/articles/1500002910622) free trial.
2. Click on a course that is provided via the subscription.
3. Run the following command to reproduce the error: ```main.py -c https://www.udemy.com/course/wpf-xaml-c-sharp/ --info```
4. See error:  
```
    Login Success
    > Fetching course information, this may take a minute...
    Downloading course information, course id not found ..
    It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
```

**Expected behavior**
Course should download the same way that purchased courses download

**Desktop**
 - OS: Windows 10
 - Python 3.9

**Additional context**
I was able to successfully download a course that I had purchased, but not for one given to me by the subscription.

**Comment by amirali1996** [comment]
By saving the course to your **watch later** list, the error will be resolved

**Comment by Puyodead1** [comment]
Looks like that plan isn't available to everyone right now, so I'm not even able to look into this. I would suggest using the above work around and if this issue becomes a problem in the future, I will come back to it

**Comment by Puyodead1** [comment]
Hello, I just added support for the Udemy pro plan, can you give the latest version a try to see if it also works for the personal plan?

Commit eb3257f3746ac6b931e3a30e94290dfd67d50277
Additional information for this feature: https://github.com/Puyodead1/udemy-downloader/#udemy-subscription-plans

**Comment by Puyodead1** [comment]
Closing this now
