### ISSUE TITLE
add support for downloading resources

### ISSUE THREAD

**Issue by Ex-Communicad0** [Puyodead1/udemy-downloader#6]
If you can please add support for download resources like udemy dl

**Comment by Puyodead1** [comment]
You should be able to use Udemy-dl with the ``--assets-only`` option. I'll take a look at adding asset support.

**Comment by Puyodead1** [comment]
An experimental implementation can be found on the ``feat-assets-qualities`` branch. a867f82f2b56840cb6942d251c5207c99dab0d9a
