### ISSUE TITLE
[BUG] Could not send HEAD request; HTTP Error 403

### ISSUE THREAD

**Issue by xDebuggerx** [Puyodead1/udemy-downloader#62]
**Describe the bug**
Upon downloading from Udemy (non-DRM course), it downloads the subtitles, but not the videos (on a particular course, it downloaded 2 videos out of around 100 - and I can't work out why it chose to download those 2 videos).

Errors:
      **> Lecture doesn't have DRM, attempting to download...**
      ====== Selected quality:  hls 1080
[generic] aa00e4239113d645bddff6d584bc0f39f04d.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjYwNTUzNC8yMDUzOTk1Ni8yMDE5LTEwLTI0XzA4LTExLTUzLWZiYjU5MWFhYTg0NTAwYjUwNzQwZDdjMWQ0ZTQ3ODkyLyIsImV4cCI6MTYzNDU4MTExNn0: Requesting header
WARNING: [generic] **Could not send HEAD request to** ... : **HTTP Error 403: Forbidden**
[generic] ... .m3u8?provider=cloudfront&token=... Downloading webpage
ERROR: [generic] **Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);** please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
    > Processing 0 asset(s) for lecture...

**To Reproduce**
As per above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
No issues with bearer token, as it is able to successfully log in and download the subtitle files.

**Comment by Puyodead1** [comment]
This was not fixed on the develop branch, I just pushed the update in commit 5d60bfe1cec01fde370edc1c97928eebfed441b9

**Comment by xDebuggerx** [comment]
****

> 
> 
> This was not fixed on the develop branch, I just pushed the update in commit [5d60bfe](https://github.com/Puyodead1/udemy-downloader/commit/5d60bfe1cec01fde370edc1c97928eebfed441b9)

Thank you!
