### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mactovia** [Puyodead1/udemy-downloader#65]
Hi, not on all but some courses i face this problem , some of lectures "only videos" are missing !! i am using latest master branch. Windows 7 32bit.

LOG
![lec2](https://user-images.githubusercontent.com/84691167/139703762-af6442c2-89b3-432b-a3e3-e4bb85c7b128.jpg)
![lect](https://user-images.githubusercontent.com/84691167/139703768-dda8322b-41d9-4ac7-bb00-5a65e4fb922f.jpg)

***  > Processing lecture 188 of 219
004 Run mode current measurement + HCLK180MHz + all peripherals enabled + ART.mp
4
      > Lecture '004 Run mode current measurement + HCLK180MHz + all peripherals
 enabled + ART' has DRM, attempting to download
> Downloading Lecture Tracks...
WARNING: You have asked for unplayable formats to be listed/downloaded. This is
a developer option intended for debugging. If you experience any issues while us
ing this option, DO NOT open a bug report
[generic] index.mpd?token=eyJ0eX..................

 Downloading 2 format(s): 6, 9
[dashsegments] Total fragments: 22
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: 004 Run mode current measurement + HCLK180MHz + all peri
pherals enabled + ART.encrypted.mp4
ERROR: unable to download video data: [Errno 2] No such file or directory: '004
Run mode current measurement + HCLK180MHz + all peripherals enabled + ART.encryp
ted.mp4.part.frag.urls'
[dashsegments] Total fragments: 22
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: 004 Run mode current measurement + HCLK180MHz + all peri
pherals enabled + ART.encrypted.m4a
ERROR: unable to download video data: [Errno 2] No such file or directory: '004
Run mode current measurement + HCLK180MHz + all peripherals enabled + ART.encryp
ted.m4a.part.frag.urls'
> Lecture Tracks Downloaded
Return code: 1
Return code from the downloader was non-0 (error), skipping!
    > Processing 0 asset(s) for lecture...
Processing 21 caption(s)...
    >  Downloading caption: '004 Run mode current measurement + HCLK180MHz + all
 peripherals enabled + ART_en.vtt'
    > Downloading File...***

**Comment by Puyodead1** [comment]
Would you be able to send me a token and the course URL to test with? either via email (puyodead@protonmail) or Discord (Puyodead1)

**Comment by mactovia** [comment]
Please check email , Thanks

**Comment by Puyodead1** [comment]
This seems to be related to the path length, windows has a limit of 260 characters, which has been causing a lot of issues for this program. I would suggest either using Linux of you can (since the path limit is 4k character), or trying this alternative branch: [id-as-course-name](https://github.com/puyodead1/udemy-downloader/tree/id-as-course-name). I also recommend moving the program a close to your harddrive root as possible, for example, `C:\udemy-downloader` as this helps reduce the path length.

**Comment by mactovia** [comment]
Thanks a lot , i use alternative branch and path  C:\ud and works fine :+1:
