### ISSUE TITLE
Some Files ignored while downloading 

### ISSUE THREAD

**Issue by post-master** [Puyodead1/udemy-downloader#66]
Some Files are ignored while downloading protected videos. KID and key are working fine but I don't know what the problem is. here are the screenshots of downloaded files https://images2.imgbox.com/29/21/aGka6hXG_o.png

Here is the log file: https://ghostbin.com/IqLxs

**Comment by Puyodead1** [comment]
The file path is too long, please see [this comment](https://github.com/Puyodead1/udemy-downloader/issues/65#issuecomment-956820278) for workarounds
