### ISSUE TITLE
[BUG] Course not downloading its logging me out

### ISSUE THREAD

**Issue by ogeeDeveloper** [Puyodead1/udemy-downloader#68]
1. I want to this course https://www.udemy.com/course/graph-theory-algorithms/learn/lecture/10794112
2. Whenever I try too download it I'm getting this error

![image](https://user-images.githubusercontent.com/74021270/140752655-3db77f48-9bef-496e-8bea-f6e94a121f49.png)

**Comment by Puyodead1** [comment]
Are you enrolled in the course?

**Comment by ogeeDeveloper** [comment]
I subscribed to it and i ca watch any development course but whenever i try to download its giving me this or the videos or encrypted

**Comment by Puyodead1** [comment]
Is this a business account?

**Comment by ogeeDeveloper** [comment]
Its a 7 da trial account. I tried to create a business account wit gale but it always fail. Could you help me i creating one of the business account

**Comment by Puyodead1** [comment]
> Could you help me i creating one of the business account
i cannot, i dont even have one myself.

> Its a 7 da trial account. 
that might be the problem, I will look into the trial and see if i can add support for it

**Comment by Puyodead1** [comment]
Please give the latest update a try. (commit eb3257f3746ac6b931e3a30e94290dfd67d50277)
Make sure to give this section a read as well: https://github.com/Puyodead1/udemy-downloader/#udemy-subscription-plans

**Comment by ogeeDeveloper** [comment]
Its working now but videos are downloading in encrypted format

**Comment by Puyodead1** [comment]
You need to have the decryption keys in the keyfile
