### ISSUE TITLE
"error": "Please accept our latest Terms of Service. How to accept ?

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#7]
i am trying to download cource, but it asking "error": "Please accept our latest Terms of Service.

![image](https://user-images.githubusercontent.com/65209890/118841212-bd6d2380-b8e5-11eb-899e-94ca1a8fe35c.png)

**Comment by pandapaddel** [comment]
udemy business? replace udemy.com url with company.udemy.com
