### ISSUE TITLE
[BUG] Error Running Script

### ISSUE THREAD

**Issue by oijm17** [Puyodead1/udemy-downloader#73]
**Describe the bug**
Error when running install modules from the script or when running the script.

**Screenshots**
<img width="1677" alt="Captura de Pantalla 2021-11-23 a la(s) 5 53 34 a  m" src="https://user-images.githubusercontent.com/5957000/143012686-8ed2bec5-f401-48b1-a98d-8847c32ae6d4.png">

**Desktop:**
 - OS: [Windows 10, Linux Centos 8.5 Stream]
 - Python: [v3.9.1,  v3.6.8]

**Additional context**
I have changed line 22 "import sgmllib, re, urlparse, sys" => "import sgmllib, re, urlparse3, sys" from "/usr/local/lib/python3.6/site-packages/sanitize.py" to the module "sanitize", which imported the module "urlparse" (requires having it installed), and it should actually be "urlparse3"

**Comment by Puyodead1** [comment]
I've recently done a fresh installation on windows 11 using python 3.10 and have not had any issues. The program does not use any pip package called sanitize, it uses [sanitize.py](https://github.com/Puyodead1/udemy-downloader/blob/master/sanitize.py)

**Comment by oijm17** [comment]
> I've recently done a fresh installation on windows 11 using python 3.10 and have not had any issues. The program does not use any pip package called sanitize, it uses [sanitize.py](https://github.com/Puyodead1/udemy-downloader/blob/master/sanitize.py)

Sorry, I just realized that for some strange reason I had some missing script files, including the sanitize.py file. However, it works fine on Windows 10, but on Linux it doesn't.
<img width="1677" alt="Captura de Pantalla 2021-11-25 a la(s) 8 33 26 a  m" src="https://user-images.githubusercontent.com/5957000/143451711-5b6dbd71-6d3c-43b1-9299-d6a9ba0e0eaf.png">

**Comment by Puyodead1** [comment]
> > I've recently done a fresh installation on windows 11 using python 3.10 and have not had any issues. The program does not use any pip package called sanitize, it uses [sanitize.py](https://github.com/Puyodead1/udemy-downloader/blob/master/sanitize.py)
> 
> Sorry, I just realized that for some strange reason I had some missing script files, including the sanitize.py file. Works fine on Windows 10; however on Linux it does not run. <img alt="Captura de Pantalla 2021-11-25 a la(s) 8 33 26 a  m" width="1677" src="https://user-images.githubusercontent.com/5957000/143451711-5b6dbd71-6d3c-43b1-9299-d6a9ba0e0eaf.png">

check your DNS and internet, that seems like an OS problem with internet connectivity

**Comment by oijm17** [comment]
> > > I've recently done a fresh installation on windows 11 using python 3.10 and have not had any issues. The program does not use any pip package called sanitize, it uses [sanitize.py](https://github.com/Puyodead1/udemy-downloader/blob/master/sanitize.py)
> > 
> > 
> > Sorry, I just realized that for some strange reason I had some missing script files, including the sanitize.py file. Works fine on Windows 10; however on Linux it does not run. <img alt="Captura de Pantalla 2021-11-25 a la(s) 8 33 26 a  m" width="1677" src="https://user-images.githubusercontent.com/5957000/143451711-5b6dbd71-6d3c-43b1-9299-d6a9ba0e0eaf.png">
> 
> check your DNS and internet, that seems like an OS problem with internet connectivity

what you mentioned is correct, now it works, thanks for the support, sorry to bother.

**Comment by Puyodead1** [comment]
No problem, glad you got it fixed!
