### ISSUE TITLE
[BUG] Unicode problems

### ISSUE THREAD

**Issue by Zeddex** [Puyodead1/udemy-downloader#74]
When I'm trying to download a course with Cyrillic filenames, I get files like this:
002 1055107710881077108410771085108510991077 1080 1089109010881086107510801081 10881077107810801084.mp4

**Comment by Puyodead1** [comment]
Please give the latest commit a try (39041ff12205995781195b0db7cfb07c641aa820). there is a new package in this update so you will need to run ``pip install -r requirements.txt`` again

**Comment by Zeddex** [comment]
Thanks, now all is good.
