### ISSUE TITLE
[BUG] Prepend class number to the attached file, instead of the identifier.

### ISSUE THREAD

**Issue by oijm17** [Puyodead1/udemy-downloader#76]
**Description**
Attached files are not downloaded by putting the class number in front of the chapter to which it belongs (as it does with videos); only a strange ID is prepended to the filename, but nothing that relates it to the class, where it was added by the instructor.

**Expected behavior**
It would be nice if the script, rename the attachments to something like this:
001 Videoclass1.mp4
001 attached file.zip
002 Videoclass2.mp4
002 iampdf.pdf
...

**Desktop:
OS: [Windows 10, Linux Centos 8.5 Stream]
Python: [v3.9.1, v3.6.8]

**Comment by Puyodead1** [comment]
Give the new commit a try (60eee56233fa89e012d6598862c7ef6ed55ea45e)

**Comment by oijm17** [comment]
> Give the new commit a try ([60eee56](https://github.com/Puyodead1/udemy-downloader/commit/60eee56233fa89e012d6598862c7ef6ed55ea45e))

You just removed the ID, the class number would be nice, preceded by the file name. I repeat the example:

001 Videoclass1.mp4
001 attached file.zip
002 Videoclass2.mp4
002 iampdf.pdf

**Comment by Puyodead1** [comment]
Ah, my bad, I understand what you are saying now.

**Comment by Puyodead1** [comment]
Alright, Lecture ids are prepended to asset names now in commit b26c8f4b5b8aca62538172928619c3f65abeb238
