### ISSUE TITLE
[BUG] ERROR: Could not find a version that satisfies the requirement sanitize_filename (from versions: none)

### ISSUE THREAD

**Issue by oijm17** [Puyodead1/udemy-downloader#77]
**Describe the bug**
Can't install sanitize_filename module mentioned in requirements.txt file, on Windows 10 it works but on Linux can't find it.

**To Reproduce**
1. Run the module installation requirements.txt

**Screenshots**
<img width="1677" alt="Captura de Pantalla 2021-11-28 a la(s) 12 20 08 a  m" src="https://user-images.githubusercontent.com/5957000/143730967-3fd568b5-d505-4826-a3e0-c07bb9e7df80.png">

**Desktop:
OS: Linux Centos 8.5 Stream
Python: v3.6.8

**Comment by Puyodead1** [comment]
sanitize-filename is only available for python 3.7+, but I don't believe that package is even used anymore in the program so try without installing it

**Comment by Puyodead1** [comment]
I've gone ahead and removed it from the requirements.txt in commit 8fb8d9f59d767aa366a96bb3277f2170a6b1b85b as it is no longer required after commit 39041ff12205995781195b0db7cfb07c641aa820
