### ISSUE TITLE
feature request, Please add one more sub directory after "out_dir"  with cource id

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#8]
I am trying to download two cources at a time ( because downloading  streams one after another in 1 videio , which takes longer time, even if i have a good internet speed  , for me it takes 5 hours per cource
but all files are going to "out_dir" folder, so it will be difficult to separate them later with respect to cource

is it possible to add one more sub folder level with cource id please

**Comment by Puyodead1** [comment]
Sure! I wanted to do that but with the course title but it isn't returned with the course data , i don't know why i didn't think of using the course id as the folder name.
