### ISSUE TITLE
[Bug]: I can't download videos that contains "Ñ,ñ,´" in their title "No such file or directory" 

### ISSUE THREAD

**Issue by BRamirez72** [Puyodead1/udemy-downloader#80]
### What happened?

I have been trying to download Spanish courses from Udemy and just noticed that the program is always skipping videos that contains "Ñ,ñ,´" in their title.

I'm getting the error: "No such file or directory" with this kind of videos.

Here you can see the error and an example of a folder missing to videos because of their title:

https://imgur.com/gallery/rC5SmQH

Pequeños
Básico
Situación
Día

### Expected Result

I expect to be able to download videos that constains "Ñ,ñ,´" in their title

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
Ah, looking at the pictures it seems like its stripping out those characters completely. I'll look into a fix within the next hour and get back to you.

**Comment by Puyodead1** [comment]
In the meantime, can you copy the original name of a lecture (from the udemy page) that has this problem and paste it here so I can use it for testing?

**Comment by BRamirez72** [comment]
Thank you very much! Yes of course.

001. Quick Tips_ Pequeños grandes consejos a la hora de modelar muros
002. Familias de Revit: lo Básico e indispensable para usarlas
003. Introducción a la sección 3
004. Menú principal de Unity
005. Ventana de Jerarquía
006. Snap entre objetos y Vértices

Ñ, ñ, á, é, í, ó & ú.

**Comment by Puyodead1** [comment]
This looks to be an issue with an external tool that is used to decrypt the files, seems that it doesn't like those characters, its actually changing them to something else which is causing the problem. I am still looking for a solution

**Comment by BRamirez72** [comment]
Hope you can fix this. Your tool seems awesome anyway.

**Comment by BRamirez72** [comment]
Hi. Any news about the solution? Thanks.

**Comment by Puyodead1** [comment]
> Hi. Any news about the solution? Thanks.

Not yet, sorry. I'll work on this either today or tomorrow

**Comment by Puyodead1** [comment]
Alright, Can you please give the [`feat-shaka`](https://github.com/Puyodead1/udemy-downloader/tree/feat-shaka) branch a try?

You will also need to download [Shaka Packager](https://github.com/google/shaka-packager/releases) (`packager-<os>-<arch>`), note that the executable needs to be named `shaka-packager` and needs to be in your path. Please let me know if this solves the problem

**Comment by BRamirez72** [comment]
Hi. I just tried it but now the program stop working after downloading some videos.
[error.txt](https://github.com/Puyodead1/udemy-downloader/files/7758839/error.txt)

**Comment by Puyodead1** [comment]
> Hi. I just tried it but now the program stops working after downloading some videos. [attachment removed]

I've removed your attachment as it contained a bearer token. These errors are most likely due to the path length being too long.
for one thing, you have the tool inside another folder `udemy-downloader-feat-shaka/udemy-downloader-feat-shaka` both with rather large names, move the tool out, and rename it to something shorter.

**Comment by BRamirez72** [comment]
Now I get a different kind of error. I renamed the folder as "1"

[error 2.txt](https://github.com/Puyodead1/udemy-downloader/files/7759024/error.2.txt)

**Comment by Puyodead1** [comment]
> Now I get a different kind of error. I renamed the folder as "1"
> 
> [attachment removed]

I don't see any errors, looks fine to me

**Comment by BRamirez72** [comment]
Oh well, but it gets stuck. I have been waiting 30 minutes but still it doesn't keep loading.

**Comment by BRamirez72** [comment]
I'll try with other courses.

**Comment by Puyodead1** [comment]
> Oh well, but it gets stuck. I have been waiting 30 minutes but still it doesn't keep loading.

Well, I'm looking at the second log you provided and its showing that its downloading everything correctly. No errors and it also doesn't look like its stuck, as the last thing in it is that it successfully decrypted a lecture. Please let me know if you are still encountering an issue.

**Comment by BRamirez72** [comment]
Hi. I have been testing the program with 4 courses more. The first course worked just fine, no problem. But the other 3 have the same issue, the program gets stuck.  When I check the last video that the program created I can open it and watch the video completly but with no audio. It seems that the video files and the audio files weren't able to mesh. 
![test](https://user-images.githubusercontent.com/95942526/147129782-53a78903-428f-4e97-ba89-27b3edde130d.JPG)
[Test.txt](https://github.com/Puyodead1/udemy-downloader/files/7764157/Test.txt)
![test 2](https://user-images.githubusercontent.com/95942526/147129784-a99f9757-5ea7-4ee8-9183-dd5b4b680bdb.JPG)
[Test 2.txt](https://github.com/Puyodead1/udemy-downloader/files/7764158/Test.2.txt)

Sorry for my bad English. Thank you.

**Comment by Puyodead1** [comment]
> Hi. I have been testing the program with 4 courses more. The first course worked just fine, no problem. But the other 3 have the same issue, the program gets stuck. When I check the last video that the program created I can open it and watch the video completly but with no audio. It seems that the video files and the audio files weren't able to mesh. ![test](https://user-images.githubusercontent.com/95942526/147129782-53a78903-428f-4e97-ba89-27b3edde130d.JPG) [attachment removed] ![test 2](https://user-images.githubusercontent.com/95942526/147129784-a99f9757-5ea7-4ee8-9183-dd5b4b680bdb.JPG) [attachment removed]
> 
> Sorry for my bad English. Thank you.

Looks like something gets stuck with merging the audio and video. Could you send me a bearer token to test with? either via email `puyodead@protonmail.com` or Discord `Puyodead1#0001`

**Comment by BRamirez72** [comment]
Nevermind I found the "solution" my bad. For some reason some videos get the program stuck and leave you 4 extra files. You just need to delete the 4 extra files and restart the program. Isn't ideal to do all this manually but it works and I thank you a lot for this. 

![1](https://user-images.githubusercontent.com/95942526/147132425-0729c409-cd99-404d-a7c5-f01c02b0f92b.JPG)

**Comment by Puyodead1** [comment]
> Nevermind I found the "solution" my bad. For some reason some videos get the program stuck and leave you 4 extra files. You just need to delete the 4 extra files and restart the program. Isn't ideal to do all this manually but it works and I thank you a lot for this.
> 
> ![1](https://user-images.githubusercontent.com/95942526/147132425-0729c409-cd99-404d-a7c5-f01c02b0f92b.JPG)

That's not suppose to happen, the program is suppose to delete those files automatically. It getting stuck is an issue

**Comment by BRamirez72** [comment]
I don't mind doing that manually, but I guess if the course it's really big is gonna take a lot of time.

Finally the last problem is that I get "Descryption returned a non-zero exit code" at least 1 time in all of the courses. Some videos just don't get decrypted. 

![image](https://user-images.githubusercontent.com/95942526/147136604-3a206a86-dd97-4d28-9b65-e3abb9dc3c4e.png)

![image](https://user-images.githubusercontent.com/95942526/147137091-0aa4b3b8-e0cb-4eed-8b9f-5973075dfc12.png)

If I can do anything to help you please let me know. I could share with you "bearer tokens" or something like that. I'll add you on Discord just in case. Thanks.

**Comment by Puyodead1** [comment]
> I don't mind doing that manually, but I guess if the course it's really big is gonna take a lot of time.
> 
> Finally the last problem is that I get "Descryption returned a non-zero exit code" at least 1 time in all of the courses. Some videos just don't get decrypted.
> 
> ![image](https://user-images.githubusercontent.com/95942526/147136604-3a206a86-dd97-4d28-9b65-e3abb9dc3c4e.png)
> 
> ![image](https://user-images.githubusercontent.com/95942526/147137091-0aa4b3b8-e0cb-4eed-8b9f-5973075dfc12.png)
> 
> If I can do anything to help you please let me know. I could share with you "bearer tokens" or something like that. I'll add you on Discord just in case. Thanks.

Yeah, I found that issue a little bit ago. Fixed in 34e847c3e6a7e855faf0239fe0fb1ed9d76f31e4

**Comment by BRamirez72** [comment]
Sorry, I didn't knew you updated the program yesterday. I re-downloaded it and is working flawlessly, no stuck error or encrypted videos. 10/10.

**Comment by eliottp1089** [comment]
> Oh well, but it gets stuck. I have been waiting 30 minutes but still it doesn't keep loading.

I have the same issue with feat-shaka

**Comment by Puyodead1** [comment]
> 

please open a new issue and provide more information, screenshots, logs, etc
