### ISSUE TITLE
[Bug]: Udemy Says:  Connection error, HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url:

### ISSUE THREAD

**Issue by caijingwen-vincent** [Puyodead1/udemy-downloader#83]
### What happened?

1. Open VPN
2. Run on the command line: python main.py -c https://www.udemy.com/course/html5-fundamentals-for-beginners

get this  error
![image](https://user-images.githubusercontent.com/71600126/146633416-83527b0d-5621-4a35-bbbf-3da5ba1d9449.png)

### Expected Result

can download the course

### Branch

master/main

**Comment by caijingwen-vincent** [comment]
Dear sir , I got this mistake, please help if you have time, thank you

**Comment by Puyodead1** [comment]
Turn off your vpn and try again

**Comment by caijingwen-vincent** [comment]
https://stackoverflow.com/questions/31639742/how-to-pass-all-pythons-traffics-through-a-http-proxy

thank you sir, I set the environment variable, now my traffic can go through vpn

$ export http_proxy="http://<user>:<pass>@<proxy>:<port>"
$ export HTTP_PROXY="http://<user>:<pass>@<proxy>:<port>"

$ export https_proxy="http://<user>:<pass>@<proxy>:<port>"
$ export HTTPS_PROXY="http://<user>:<pass>@<proxy>:<port>"
