### ISSUE TITLE
[Bug]: The program gets stuck

### ISSUE THREAD

**Issue by eliottp1089** [Puyodead1/udemy-downloader#84]
### What happened?

The program gets stuck after downloading some videos. 

![freeze](https://user-images.githubusercontent.com/22084144/147422887-95425e0c-4259-4f10-afee-c844b1b83854.PNG)
![picture2](https://user-images.githubusercontent.com/22084144/147423118-1e1db4cf-37e8-49e3-86e2-9373045367d2.PNG)

Log [2021-12-26-05-47-15.log](https://github.com/Puyodead1/udemy-downloader/files/7777740/2021-12-26-05-47-15.log)

### Expected Result

I expect to be able to download videos that constains "Ñ,ñ,´" in their title

### Branch

master/feat-shaka

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
Can you please give the latest commit on the feat-shaka branch a try? I pushed a fix for something that might be the reason for this or at least contribute to it (72a354ed69029a56453058f91f8356a18a248063)

**Comment by eliottp1089** [comment]
> Can you please give the latest commit on the feat-shaka branch a try? I pushed a fix for something that might be the reason for this or at least contribute to it ([72a354e](https://github.com/Puyodead1/udemy-downloader/commit/72a354ed69029a56453058f91f8356a18a248063))

Is working, no stuck error anymore, thank you!
