### ISSUE TITLE
[Bug]: > Return code from the decrypter was non-0 (error), skipping!

### ISSUE THREAD

**Issue by BRamirez72** [Puyodead1/udemy-downloader#86]
### What happened?

Hi. Some video files aren't getting decrypted, what can I do about this? Thanks.
![1](https://user-images.githubusercontent.com/95942526/147673048-ec808af5-21c0-424a-89c9-a9284435d994.png)
![2](https://user-images.githubusercontent.com/95942526/147673053-674797db-ef25-45f0-a2a3-64849bf5b479.png)

### Expected Result

The videos should get decrypted in audio and video format and then mixed together.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by superman2197** [comment]
I am also getting the same issue.
As the thread is still open, I will keep checking it and once it is fixed, will try again.

**Comment by Puyodead1** [comment]
> ### What happened?
> 
> Hi. Some video files aren't getting decrypted, what can I do about this? Thanks. ![1](https://user-images.githubusercontent.com/95942526/147673048-ec808af5-21c0-424a-89c9-a9284435d994.png) ![2](https://user-images.githubusercontent.com/95942526/147673053-674797db-ef25-45f0-a2a3-64849bf5b479.png)
> ### Expected Result
> 
> The videos should get decrypted in audio and video format and then mixed together.
> ### Branch
> 
> master/main
> ### What operating systems are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> _No response_
> ### Other information
> 
> _No response_

Please try the `feat-shaka` branch. this branch uses a different program for decryption that is much more stable, the current one used in the master branch has issues with languages other than English. You will need to get shaka-packager executable for your system (windows by the looks of it) and put it in your system path

Shaka-Packager: https://github.com/google/shaka-packager/releases/latest
Feat-Shaka Branch: https://github.com/Puyodead1/udemy-downloader/tree/feat-shaka

**Comment by BRamirez72** [comment]
Thanks, now is working normally.
