### ISSUE TITLE
[Bug]: decryption process return M4A Audio file + mp4 Video file and they don't work

### ISSUE THREAD

**Issue by mzughbor** [Puyodead1/udemy-downloader#88]
### What happened?

I think there is an issue with decryption process because the end result with some of drm videos will be audio M4A format file and video named with .**encrypted**  at the end of the name ??
and these file actually dose not work on any video player at all 
So how we can merge them or decrypt this thing ?? 
any **solutions** any ideas ?

see[this img]( https://ibb.co/cJpZ1kt)

### Expected Result

one video file ! and working 

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by superman2197** [comment]
@mzughbor, the same was reported in here (https://github.com/Puyodead1/udemy-downloader/issues/86).
I tried "feat-shaka" branch but issue is still there. All the binaries are in place. I can upload them if required.

[02:49:45] [udemy-downloader] [parse_new:1382] INFO:   > Processing lecture 19 of 325
[02:49:45] [udemy-downloader] [parse_new:1382] INFO:   > Processing lecture 20 of 325
[02:49:45] [udemy-downloader] [process_lecture:1288] INFO:       > Lecture '013 NEW - Lab - Deploying a Linux machine - SSH keys' has DRM, attempting to download
[02:49:45] [udemy-downloader] [handle_segments:1081] INFO: > Downloading Lecture Tracks...
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[generic] index.mpd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoib3V0L3YxLzJjMzQyZmUyMDAwMzRiZDNiM2VlZDZhYWEzMmRiMTc0LzkxMjQyYTcyYzBmYTQwM2Y4YWNjZDcwMWE4OWM3MGEzLzJmNWViNjRkOTc3YjRkN2M4ZGIxZGI4MTIyNDFjM2M5LyIsImV4cCI6MTY0MTA0MzgwNn0: Requesting header
WARNING: [generic] Forcing on generic information extractor.


![image](https://user-images.githubusercontent.com/43517093/147847705-cee7237f-2333-4777-bd07-40bca22bcda6.png)

**Comment by Puyodead1** [comment]
> ### What happened?
> 
> I think there is an issue with decryption process because the end result with some of drm videos will be audio M4A format file and video named with .**encrypted** at the end of the name ?? and these file actually dose not work on any video player at all So how we can merge them or decrypt this thing ?? any **solutions** any ideas ?
> 
> see[this img](https://ibb.co/cJpZ1kt)
> ### Expected Result
> 
> one video file ! and working
> ### Branch
> 
> master/main
> ### What operating systems are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> _No response_
> ### Other information
> 
> _No response_

@mzughbor Please try the `feat-shaka` branch, this requires [shaka-packager](https://github.com/google/shaka-packager/releases) which is much more stable for decryption



> @mzughbor, the same was reported in here (#86). I tried "feat-shaka" branch but issue is still there. All the binaries are in place. I can upload them if required.
> 
> [02:49:45] [udemy-downloader] [parse_new:1382] INFO: > Processing lecture 19 of 325 [02:49:45] [udemy-downloader] [parse_new:1382] INFO: > Processing lecture 20 of 325 [02:49:45] [udemy-downloader] [process_lecture:1288] INFO: > Lecture '013 NEW - Lab - Deploying a Linux machine - SSH keys' has DRM, attempting to download [02:49:45] [udemy-downloader] [handle_segments:1081] INFO: > Downloading Lecture Tracks... WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging. If you experience any issues while using this option, DO NOT open a bug report [generic] index.mpd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoib3V0L3YxLzJjMzQyZmUyMDAwMzRiZDNiM2VlZDZhYWEzMmRiMTc0LzkxMjQyYTcyYzBmYTQwM2Y4YWNjZDcwMWE4OWM3MGEzLzJmNWViNjRkOTc3YjRkN2M4ZGIxZGI4MTIyNDFjM2M5LyIsImV4cCI6MTY0MTA0MzgwNn0: Requesting header WARNING: [generic] Forcing on generic information extractor.
> 
> ![image](https://user-images.githubusercontent.com/43517093/147847705-cee7237f-2333-4777-bd07-40bca22bcda6.png)
> 
> Binaries: E:\Softwares\PORTABLE_SOFTWAREs\Scripts\udemy-downloader-feat-shaka>dir | findstr exe 12/31/2021 02:06 313,856 aac2mp4.exe **[12/31/2021 02:19 5,596,672 aria2c.exe]** **[12/30/2021 17:28 119,018,496 ffmpeg.exe]** 12/30/2021 17:28 118,882,816 ffplay.exe **[12/30/2021 17:28 118,917,632 ffprobe.exe]** for metadata 12/31/2021 02:06 314,880 mp42aac.exe 12/31/2021 02:06 315,904 mp42avc.exe 12/31/2021 02:06 316,416 mp42hevc.exe 12/31/2021 02:06 355,328 mp42hls.exe 12/31/2021 02:06 330,240 mp42ts.exe 12/31/2021 02:06 316,416 mp4audioclip.exe 12/31/2021 02:06 317,952 mp4compact.exe 12/31/2021 02:06 306,688 mp4dcfpackager.exe **[12/31/2021 02:06 365,568 mp4decrypt.exe]** 12/31/2021 02:06 312,832 mp4diff.exe 12/31/2021 02:06 327,680 mp4dump.exe 12/31/2021 02:06 324,608 mp4edit.exe 12/31/2021 02:06 431,616 mp4encrypt.exe 12/31/2021 02:06 289,792 mp4extract.exe 12/31/2021 02:06 346,112 mp4fragment.exe 12/31/2021 02:06 314,880 mp4iframeindex.exe 12/31/2021 02:06 363,008 mp4info.exe 12/31/2021 02:06 414,720 mp4mux.exe 12/31/2021 02:06 324,608 mp4pssh.exe 12/31/2021 02:06 312,832 mp4rtphintinfo.exe 12/31/2021 02:06 307,712 mp4split.exe 12/31/2021 02:06 330,240 mp4tag.exe **[01/01/2022 14:03 2,758,656 mpd_generator-win-x64.exe]** came with Shaka-packager so kept it. **[01/01/2022 12:45 4,503,040 shaka-packager.exe]** **[12/31/2021 02:53 12,805,066 yt-dlp.exe]**
> 
> E:\Softwares\PORTABLE_SOFTWAREs\Scripts\udemy-downloader-feat-shaka>

@superman2197 I've pushed some updates to that branch recently, please pull the latest commits and try again with `--log-level DEBUG` appended to your command. If you still have the issue, please upload the log file.

**Comment by mzughbor** [comment]
@superman2197  Hi 
superman2197 >>  Shaka Packager is missing from your system or path!
I'm sure it's there and I check that by typing name in cmd any ideas @Puyodead1 
 I think there is something else not just binaries it's essential for windows OS !!

**Comment by Puyodead1** [comment]
> @superman2197 Hi superman2197 >> Shaka Packager is missing from your system or path! I'm sure it's there and I check that by typing name in cmd any ideas @Puyodead1 I think there is something else not just binaries it's essential for windows OS !!

are you able to type the command in cmd and get an output?

**Comment by mzughbor** [comment]
yah 
![image](https://user-images.githubusercontent.com/43893822/148157196-75878273-a0eb-4011-a261-27da231cbeb1.png)

**Comment by Puyodead1** [comment]
> yah ![image](https://user-images.githubusercontent.com/43893822/148157196-75878273-a0eb-4011-a261-27da231cbeb1.png)

what happens when you run the script now?

**Comment by Puyodead1** [comment]
oh, its named incorrectly. it needs to be named `shaka-packager`

**Comment by mzughbor** [comment]
![image](https://user-images.githubusercontent.com/43893822/148157413-0f41863f-b21b-43e3-9423-62e5723cdb0b.png)
 oh yah ok so how we can add this thing our system or make sure its set up and on the path there ?

**Comment by mzughbor** [comment]
is it this ??
https://github.com/google/shaka-packager/releases 
and then just add it to path as aria2 and so on ?

**Comment by Puyodead1** [comment]
> is it this ?? https://github.com/google/shaka-packager/releases and then just add it to path as aria2 and so on ?

yes

**Comment by mzughbor** [comment]
![Screenshot (268)](https://user-images.githubusercontent.com/43893822/148159130-9fceb7c5-7edf-4134-9e45-455edd94e194.png)
 look 
![Screenshot (269)](https://user-images.githubusercontent.com/43893822/148159133-7dc81f6b-4185-4f6a-ae1c-d98c1b641ce8.png)
?? is that right ? cause I still get the error

**Comment by mzughbor** [comment]
and I reboot my window too, any ideas please ?

**Comment by Puyodead1** [comment]
> and I reboot my window too, any ideas please ?

you still didnt name it correctly, the exe file needs to be `shaka-packager`

**Comment by mzughbor** [comment]
oh no, ok it's done right, let's see if it will get all drm videos!
thanks @Puyodead1

**Comment by mzughbor** [comment]
@Puyodead1  it's worked, I'm getting one video file and it's run without any issues about decryption, thanks again, great work man

**Comment by superman2197** [comment]
@Puyodead1, sorry for the delayed response. There is too much work this week. I will check later today or on weekends and keep you apprised.

Thank you!

**Comment by Puyodead1** [comment]
> @Puyodead1, sorry for the delayed response. There is too much work this week. I will check later today or on weekends and keep you apprised.
> 
> Thank you!

No problem!

**Comment by Abdelraman** [comment]
![image](https://user-images.githubusercontent.com/4821833/148661669-a575b2f6-f8a5-4cb8-8f28-83a97267774c.png)
same issue here, installed shaka-packager, added to envir. variables 
![image](https://user-images.githubusercontent.com/4821833/148661688-47c33162-6cbd-42da-b61d-ab5e725231c9.png)
used the branch feat shaka, but still the same issue appears,

**Comment by Puyodead1** [comment]
> ![image](https://user-images.githubusercontent.com/4821833/148661669-a575b2f6-f8a5-4cb8-8f28-83a97267774c.png) same issue here, installed shaka-packager, added to envir. variables ![image](https://user-images.githubusercontent.com/4821833/148661688-47c33162-6cbd-42da-b61d-ab5e725231c9.png) used the branch feat shaka, but still the same issue appears,

use `--log-level DEBUG` and post a log

**Comment by Abdelraman** [comment]
![image](https://user-images.githubusercontent.com/4821833/148662008-ba6e5b16-6508-42fb-b7a2-2ac16ed1134b.png)

![image](https://user-images.githubusercontent.com/4821833/148662039-d3677811-fe7f-4e3a-b02a-3f727808651e.png)

**Comment by Abdelraman** [comment]
Thanks a lot man, the issue was the key was not correct, now working as expected even from the main branch, thanks for your efforts

**Comment by superman2197** [comment]
Hi @Puyodead1,

Used the latest feat-shaka version, still same error. I have collected the logs but as this is business account I have masked the sub-domain name with *********. 

shaka-packager.exe is also in place.

![image](https://user-images.githubusercontent.com/43517093/149662609-2238a547-11c8-4df9-994d-1e122fe130ff.png)

Logs- https://drive.google.com/file/d/1_gnZGWDzNmt7OvZs99rw_9u8fQ_jTekr/view

**Comment by Puyodead1** [comment]
> Hi @Puyodead1,
> 
> Used the latest feat-shaka version, still same error. I have collected the logs but as this is business account I have masked the sub-domain name with *********.
> 
> ![image](https://user-images.githubusercontent.com/43517093/149663093-985b66b3-49f9-418d-90c3-c8f7110eba3e.png)
> 
> shaka-packager.exe is also in place.
> 
> ![image](https://user-images.githubusercontent.com/43517093/149662609-2238a547-11c8-4df9-994d-1e122fe130ff.png)
> 
> [2022-01-16-06-45-10_Masked.zip](https://github.com/Puyodead1/udemy-downloader/files/7877070/2022-01-16-06-45-10_Masked.zip)

I've updated the master branch which adds shaka, plus various other fixes including better debug logging, can you please update to the latest version of master and try again with `--log-level DEBUG`. This time, it will print out what the external tools display which will also include errors so it should be much easier to see the problem.

**Comment by superman2197** [comment]
> 

I checked everything from scratch. It seems the issue was with the environment variables. Corrected it and now I see something different.  Now shaka-packager is trying to merge files but it is stuck for 1 hr. Logs attached.

My system has 4 core 4 thread i5 8th gen with 32gig ram,1.5tb SSD and 4bg 1550ti dedicated graphics if that matters.

![image](https://user-images.githubusercontent.com/43517093/150010423-676afae5-9c9e-4224-805f-58b993e0c373.png)
[Timezone is IST]

[2022-01-19-12-04-46.zip](https://github.com/Puyodead1/udemy-downloader/files/7892069/2022-01-19-12-04-46.zip)

**Comment by Puyodead1** [comment]
Alright, I'm going to start looking into this now.

**Comment by Puyodead1** [comment]
I'm going to close this issue. For issues related to merging being stuck, follow the progress on #107
