### ISSUE TITLE
[Bug]: Error Converting: 'gbk' codec can't encode character

### ISSUE THREAD

**Issue by caijingwen-vincent** [Puyodead1/udemy-downloader#90]
### What happened?

1. Download course
2. Download subtitle like srt format
3. In rare cases, the error shown in the figure below will occur
4. This error will cause the corresponding subtitle file to be empty

![image](https://user-images.githubusercontent.com/71600126/147858783-380ea5a0-951e-46fd-a4b2-02c6063e8146.png)

### Expected Result

There will be no errors in the picture, and the subtitles can be downloaded normally

### Branch

master/main

**Comment by caijingwen-vincent** [comment]
When I redownload the captions , the captions will download correctly. 

**here below is what I type to download:**
python main.py -c https://www.udemy.com/course/shipping-from-alibaba-to-amazon-fba-alibaba-training-course/ --download-assets --download-captions --skip-hls --disable-ipv6

**here below is what I type to redownload :**
python main.py -c https://www.udemy.com/course/shipping-from-alibaba-to-amazon-fba-alibaba-training-course/ --skip-lectures --download-captions

**Comment by Puyodead1** [comment]
I've push some new commits that have most debugging stuff, please try with the `--log-level DEBUG` option added and post the resulting log file, this should have more information to find the issue.
