### ISSUE TITLE
[Bug]: Error converting caption: [WinError 2] System can't found specify file

### ISSUE THREAD

**Issue by caijingwen-vincent** [Puyodead1/udemy-downloader#91]
### What happened?

Dear Sir:

1. Download course
2. Download subtitle like srt format
3. In rare cases, the error shown in the figure below will occur
4. This error will cause the corresponding subtitle file to be empty

![image](https://user-images.githubusercontent.com/71600126/147858914-aaecf81c-4801-496f-8b46-ceb225b02806.png)

### Expected Result

There will be no errors in the picture, and the subtitles can be downloaded normally

### Branch

master/main

**Comment by caijingwen-vincent** [comment]
When I redownload the captions , the captions will download correctly.

here below is what I type to download:
python main.py -c https://www.udemy.com/course/shipping-from-alibaba-to-amazon-fba-alibaba-training-course/ --download-assets --download-captions --skip-hls --disable-ipv6

here below is what I type to redownload :
python main.py -c https://www.udemy.com/course/shipping-from-alibaba-to-amazon-fba-alibaba-training-course/ --skip-lectures --download-captions

**Comment by Puyodead1** [comment]
I've push some new commits that have most debugging stuff, please try with the `--log-level DEBUG` option added and post the resulting log file, this should have more information to find the issue.

**Comment by Abdelraman** [comment]
![image](https://user-images.githubusercontent.com/4821833/148659909-350f20de-9918-4557-a85c-efc3b6951d14.png)

same error here

**Comment by Puyodead1** [comment]
> ![image](https://user-images.githubusercontent.com/4821833/148659909-350f20de-9918-4557-a85c-efc3b6951d14.png)
> 
> same error here

helps to read and follow the README... you are missing yt-dlp

**Comment by Abdelraman** [comment]
![image](https://user-images.githubusercontent.com/4821833/148660123-c59a4256-130e-4041-b654-0045b218ac19.png)
Thanks for your quick response but it is already installed

**Comment by Abdelraman** [comment]
![image](https://user-images.githubusercontent.com/4821833/148660123-c59a4256-130e-4041-b654-0045b218ac19.png)
Thanks for your quick response but it is already installed

**Comment by Puyodead1** [comment]
> ![image](https://user-images.githubusercontent.com/4821833/148660123-c59a4256-130e-4041-b654-0045b218ac19.png) Thanks for your quick response but it is already installed

as the readme says, it needs to be in your path so that its executable just by typing `yt-dlp`

**Comment by Abdelraman** [comment]
yes it seems that it was installed but not in the environment variables. Thanks

**Comment by sivaparvathigoli5** [comment]
any one please tell me how to get the Decryption Key ID
Decryption Key

**Comment by tegabom** [comment]
You can contact me for full working version of O11 OTT Streamer V2!!! Latest Build!!!

https://t.me/zaddyst

- License Offline and install Unlimited servers
- Script Autoinstall and Autorestart
O11 v2 supports 5 running modes
- Internal remuxer
- FFmpeg resident
- FFmpeg TS HLS/Direct
- FFmpeg MultiTS HLS
- FMP4 HL
O11 v2 supports 5 output modes
- HLS/Direct
- SRT Server
- Custom Pipe
- UDP/SRT Push
- MPEGTS
Ondemand function
- Network Params
- HTTP/SOCKS5 Proxy
- Bind
- DNS over HTTPS
- Script,Manifest,Media files
Scripts
action=manifest - Manifest script
action=cdm drm=[widevine or playready] cdm=[internal or external] challenge=[drm challenger] pssh=[pssh used to extract needed keys] - Cdm script
action=events - Events
action=channels - Channels
action - Heartbeat
