### ISSUE TITLE
How to download without Udemy finding out?

### ISSUE THREAD

**Issue by aldwnesx** [Puyodead1/udemy-downloader#95]
I want to download some courses from Udemy for my personal use only, considering in the past they removed some courses I was watching halfway, and they refunded me with credits that I couldn't spend on unless courses were on sale.

I do not want to risk being caught and getting banned.. anyway to reduce the risk or prevent them from detecting e.g downloading x videos over y time?

**Comment by Puyodead1** [comment]
They shouldn't ban you unless you try to refund the course. Nobody has been banned for downloading courses as far as I'm aware.

**Comment by atorralb** [comment]
use atube catcher
https://www.atube.me/
