### ISSUE TITLE
[Bug]: some video cant convert decryot

### ISSUE THREAD

**Issue by mahdisky** [Puyodead1/udemy-downloader#98]
### What happened?

some video cant convert decryot
this error

[11:43:50] [udemy-downloader] [handle_segments:1150] INFO: > Decrypting video, this might take a minute...
ERROR: cannot open input file (003 1.3 û Carrier and Generic Communication System.encrypted.mp4) -4
[11:43:50] [udemy-downloader] [handle_segments:1153] ERROR: > Return code from the decrypter was non-0 (error), skipping!

### Expected Result

encrypt all video

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment]
ensure you have the proper KeyID and Key in the keyfile.json. otherwise, use `--log-level DEBUG` and post the log

**Comment by mahdisky** [comment]
Do you mean this? 
[log.txt](https://github.com/Puyodead1/udemy-downloader/files/7856689/log.txt)

**Comment by Puyodead1** [comment]
> Do you mean this? [log.txt](https://github.com/Puyodead1/udemy-downloader/files/7856689/log.txt)

That file is hardly readable, there should be a logs folder that has a file for every time you run the program, use the log-level option and then upload the latest log file in that folder

**Comment by mahdisky** [comment]
[2022-01-12-05-03-07.log](https://github.com/Puyodead1/udemy-downloader/files/7857044/2022-01-12-05-03-07.log)

**Comment by Puyodead1** [comment]
> [2022-01-12-05-03-07.log](https://github.com/Puyodead1/udemy-downloader/files/7857044/2022-01-12-05-03-07.log)

thanks, did you enable debug logging?

**Comment by mahdisky** [comment]
oh no i forget
i send again

**Comment by mahdisky** [comment]
[2022-01-12-11-20-35.log](https://github.com/Puyodead1/udemy-downloader/files/7857704/2022-01-12-11-20-35.log)

**Comment by Puyodead1** [comment]
> [2022-01-12-11-20-35.log](https://github.com/Puyodead1/udemy-downloader/files/7857704/2022-01-12-11-20-35.log)

Thanks, I've found where the error comes from, just so I can test before pushing the fix, can you upload `019 6.3.3-8-PSK_en.vtt`?

**Comment by Puyodead1** [comment]
I've pushed a possible fix for the caption conversion error, please give that a try.

**Comment by mahdisky** [comment]
ya thnks , captions its true,
but video convert for some video not decrypt
It is in the top log
sample :
003 1.3 – Carrier and Generic Communication System.encrypted.m4a
003 1.3 – Carrier and Generic Communication System.encrypted.mp4

**Comment by Puyodead1** [comment]
> ya thnks , captions its true, but video convert for some video not decrypt It is in the top log sample : 003 1.3 – Carrier and Generic Communication System.encrypted.m4a 003 1.3 – Carrier and Generic Communication System.encrypted.mp4

Maybe I'm just overlooking it, but I don't see this in any of the logs provided. But in most cases, this is caused by the decryption key/key id pair not being in the keyfile (or being entered incorrectly)

**Comment by mahdisky** [comment]
I used the key/key id correctly but it does not work for some videos,
For example, he did not codify one of his lessons in this course, but he decoded the rest of the lessons

**Comment by mahdisky** [comment]
[2022-01-14-09-19-48.log](https://github.com/Puyodead1/udemy-downloader/files/7868149/2022-01-14-09-19-48.log)
 
just its leason cant decrypt or convert :
003 1.3 – Carrier and Generic Communication System.encrypted.m4a
003 1.3 – Carrier and Generic Communication System.encrypted.mp4

**Comment by mahdisky** [comment]
can you help me?

**Comment by Puyodead1** [comment]
Master branch has been updated, please pull the new changes and make sure to install the new dependency (shaka-packager - https://github.com/google/shaka-packager/releases/latest)

Use --log-level after updating, if you have an error still, post the log. this time, the log will show the output from the decryption program so I can see exactly what the problem is.

**Comment by mahdisky** [comment]
its stop work here 
not continue
[2022-01-17-04-15-48.log](https://github.com/Puyodead1/udemy-downloader/files/7881346/2022-01-17-04-15-48.log)

**Comment by emresaizou** [comment]
How did you get kid?
Are you sure kid is correct?

**Comment by Samhunter91** [comment]
> I used the key/key id correctly but it does not work for some videos, For example, he did not codify one of his lessons in this course, but he decoded the rest of the lessons

Are you stil able to obtain kid and key?

**Comment by d1mGen** [comment]
> I used the key/key id correctly but it does not work for some videos, For example, he did not codify one of his lessons in this course, but he decoded the rest of the lessons

can you tell please how it finding! **(kid and key)**

**Comment by taqiraza** [comment]
Someone please guide how to aquire the key and key ID
